### ISSUE TITLE
Rearrange widgets

### ISSUE THREAD

**Issue by FraserEmbrey** [Jean-Tinland/simple-bar#100]
Is it possible to rearrange the widgets? I know I can reorder them in data.jsx but it seems like the goal is to edit these things in the settings GUI.

**Comment by Jean-Tinland** [comment]
I could indeed add an option in settings. 
Otherwise, as the data widget is in a `flex` layout you can add an `order: x;` on each sub-widget selector in the `CustomStyles.jsx` file.

Let me know what's suits you most.

**Comment by FraserEmbrey** [comment]
Setting the order in CustomStyles.jsx is good for me.

**Comment by bbamnesia** [comment]
> I could indeed add an option in settings. Otherwise, as the data widget is in a `flex` layout you can add an `order: x;` on each sub-widget selector in the `CustomStyles.jsx` file.
> 
> Let me know what's suits you most.

Im confused on what you mean by this, where can I find the CustomStyles.jsx file?
