### ISSUE TITLE
Can't switch spaces from the widget in Big Sur

### ISSUE THREAD

**Issue by TheCultLeader666** [Jean-Tinland/simple-bar#102]
Ever since I updated my mac to macOS 11, I have no longer been able to switch spaces by clicking on the space number in the widget. In addition, the widget doesn't update unfocused spaces.

**Comment by Jean-Tinland** [comment]
Hi, did you check the yabai wiki after updating to Big Sur?
There is some changes to do after updating, [see here](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup) for more information.

Let me know if this helps you.

**Comment by TheCultLeader666** [comment]
Yeah, thanks :)
