### ISSUE TITLE
Error handling for when https://wttr.in/ isn't available. 

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#103]
Hi Jean , 

I have run into an issue today due to https://wttr.in/ unable to parse new requests due to their DB capacity. 

simple-bar-data was refusing to load with a JSON error till I removed my location and disabled the widget. 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/2527231/108133933-47e69100-7105-11eb-8e77-7667c235d862.png">

Thanks, 

Miko

**Comment by Jean-Tinland** [comment]
Hi!

Thanks for your message.
The weather service was indeed down yesterday, I also disable the widget in settings until it was fixed.
I'll update the `get_data` script to handle this use case.

**Comment by MikoMagni** [comment]
@Jean-Tinland  thank you

**Comment by Jean-Tinland** [comment]
PR #112 has normally solved this issue. :)
