### ISSUE TITLE
clarification on usage

### ISSUE THREAD

**Issue by yangkennyk** [Jean-Tinland/simple-bar#104]
So I have the plugin working but some things weren't entirely clear in the documentation 

- Is simple bar meant to be used with "Auto Hide Menubar" enabled?
- By default simple bar is hidden beneath my windows so I had to set top padding in my yabairc. Is that supposed to be the case?
- When I set to "floating" mode, simple bar is still hidden beneath my windows unless I add the top padding to yabairc. This ends up being the same as if I didn't enable floating mode. Should it be floating on top of my yabai windows by default?

I learned how to use yabai a couple weeks ago and I'm excited to use simple bar to help me navigate my spaces. Thanks for releasing this plugin!

**Comment by Jean-Tinland** [comment]
Hi,

- Aesthetically speaking, I find simple-bar better displayed without the system menubar. If you don't use this option, simple-bar will be rendered below the menubar. You can choose what suits you better.
- There is an option `external_bar` that you can set in your .yabairc. See my config below as an example:
```shell
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config external_bar                 all:28:0
```
- simple-bar is made to work along side yabai in "stack" or "bsp" modes with the `external_bar` setting. I should specify that in the readme file.

Sorry for my late response and thank you for the compliments, I'm glad it suits you well!
