### ISSUE TITLE
HowTo: set space name

### ISSUE THREAD

**Issue by junwei-wang** [Jean-Tinland/simple-bar#107]
By default, each space has a index before the application icons. In the gallery, it seems that it is possible to replace the index by a name. How to do this?

<img width="1680" alt="1" src="https://user-images.githubusercontent.com/866329/109971228-4799e880-7cf6-11eb-99bd-a7f982c1009e.png">

**Comment by Jean-Tinland** [comment]
You can do this thanks to yabai:

```shell
yabai -m space X --label MY_SPACE_NAME
```
Where X is the space number you want to rename.
See [yabai wiki](https://github.com/koekeishiya/yabai/wiki/Commands#label-spaces) for more info.

You'll find below a wrapper function refreshing simple bar right after space renaming:
```shell
function rename_space() {
  yabai -m space $1 --label $2
  osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "simple-bar-spaces-jsx"'
}
# usage: rename_space X MY_SPACE_NAME
# Where X is the space number you want to rename
```
You can add this to yours `.bashrc` or `.zshrc`.

**Comment by junwei-wang** [comment]
Thank you very much!
