### ISSUE TITLE
Removing space switch animation

### ISSUE THREAD

**Issue by strafe** [Jean-Tinland/simple-bar#108]
I've had a poke around in the theme and tried to override several things but can't seem to do this one. I'm pretty sure it's being affected by the ease setting though and I'd love to have it update the current space as fast as possible.

**Comment by Jean-Tinland** [comment]
You can override `simple-bar` styles in the CustomStyles.js file.

If you want to remove all transitions on spaces elements, use the CSS below:

```javascript
const CustomStyles = /* css */ `
.space__inner,
.spaces__add {
  transition: none !important;
}
`

export default CustomStyles
```

Let me know if this is usefull.

**Comment by strafe** [comment]
@Jean-Tinland that's great thank you!

Also I don't want to spam issues so I'll just tack on an extra question if that's alright. Is it expected that the space hover controls will go behind the windows? It's not too noticeable here but if the gap is smaller it can hardly be seen.
<img width="76" alt="image" src="https://user-images.githubusercontent.com/15663890/110182551-e0b72500-7e04-11eb-952a-c05e77155d8e.png">

**Comment by Jean-Tinland** [comment]
Yes it is expected as Übersicht is displaying its widgets on the desktop, under all opened apps.

There is an option "Inline spaces options" that you can toggle in settings. 

See screenshot below:
<img width="571" alt="Screenshot 2021-03-06 at 11 13 59" src="https://user-images.githubusercontent.com/43068795/110216197-05b3a280-7eae-11eb-8594-8de436cb3b7b.png">

I'm not really satisfied of the appearance of these options when inlined but it solves the app overlapping issue.

**Comment by strafe** [comment]
Ah great! Only other thing I've noticed is that the browser current track doesn't work for me, I'm assuming it's meant to be similar to the Spotify one but nothing shows up. I see it supposedly supports Safari and YouTube but wasn't working for me.

**Comment by Jean-Tinland** [comment]
That's weird, I just tried to open a Youtube video in Safari and it was displayed correctly in simple-bar.

After installing simple-bar you should have been prompted to allow Übersicht to request data from safari with applescript. It may simply be a permission problem.

**Comment by strafe** [comment]
Hmm, I'm pretty sure I said yes to all prompts:
<img width="668" alt="Screenshot 2021-03-09 at 14 58 11" src="https://user-images.githubusercontent.com/15663890/110490121-e86a1880-80e7-11eb-9e8a-6b2278e630b8.png">

**Comment by Jean-Tinland** [comment]
I suppose Safari is also checked?
![image](https://user-images.githubusercontent.com/43068795/110913192-1e401480-8315-11eb-82c6-bcc0dc6e196e.png)

I'll investigate more, I don't really know what is happening here. I'll keep you updated if I find something.

**Comment by strafe** [comment]
@Jean-Tinland Safari is not checked, in fact it does not appear there at all. I have uninstalled and reinstalled Ubersicht a few times, making sure to completely reset my automation permissions between (`tccutil reset AppleEvents`) and Ubersicht just never asks to control Safari.

It does ask to control Spotify, but never Safari. Maybe it works for you from a previous version but changes the the current version mean it will never ask to control Safari?
