### ISSUE TITLE
error after updating to macos 11.2.3

### ISSUE THREAD

**Issue by maishams** [Jean-Tinland/simple-bar#114]
hi! after updating i get this error:

![Screenshot 2021-03-12 at 09 57 46](https://user-images.githubusercontent.com/43148755/110924104-8d1f6c80-8319-11eb-99c6-a298d8fb3b2f.png) i've tried refreshing and restarting.

any help on fixing this would be great :)

**Comment by Jean-Tinland** [comment]
It looks like your settings are corrupted. I must say I don't know how it could be. 

You could try to open the Übersicht Debug Console then go in  > `Foreground tab` > `Storage` > `Local Storage` and remove  the `simple-bar-settings` row. It will reset your settings. You can refresh all widgets after that.

Let me know if this is helping.

**Comment by Jean-Tinland** [comment]
I'm closing this issue for now, feel free to re open it if necessary.
