### ISSUE TITLE
Error while executing browser_audio.applescript

### ISSUE THREAD

**Issue by strafe** [Jean-Tinland/simple-bar#115]
The browser track widget is not working for me, I have found that if I modify the `browser_audio.applescript` script by removing the Google Chrome section, it will start working (I do not have Google Chrome installed).

Default script (exit code 1):
```
browser_audio.applescript:617:620: script error: Expected class name but found property. (-2741)
```

Google Chrome block removed (exit code 0):
```
{ "browser": "safari", "title": "Video Title" }
```

**Comment by Jean-Tinland** [comment]
I wrapped the Google Chrome part in a try/catch. This should work as expected now.

I must say I didn't anticipate about that issue: obviously not everybody is using Google Chrome. Sorry for that :)

Let me know if this solves the issue.

**Comment by strafe** [comment]
Looks good, is it meant to be `Google Chromed` with a `d` on the end?
https://github.com/Jean-Tinland/simple-bar/blob/f9ca219e9f49a70096cac716fa336bf2122d0f2a/lib/scripts/browser_audio.applescript#L15

**Comment by strafe** [comment]
Oh also this new script gives me the exact same error:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15663890/110932411-5f3f2580-8323-11eb-84b2-202db2a0da84.png">

**Comment by Jean-Tinland** [comment]
> Looks good, is it meant to be `Google Chromed` with a `d` on the end?
> https://github.com/Jean-Tinland/simple-bar/blob/f9ca219e9f49a70096cac716fa336bf2122d0f2a/lib/scripts/browser_audio.applescript#L15

Oops, that's a typo.

Weird, I'll look into it.

**Comment by Jean-Tinland** [comment]
I'll close this for now, feel free to re open it if necessary!

**Comment by jorpilo** [comment]
Hello

I do not have Google Chrome installed but I have Brave Browser. I have double checked the browser-audio file and with the typo fixed the error is still present

```
➜  simple-bar git:(master) ✗ osascript ./lib/scripts/browser-audio.applescript
./lib/scripts/browser-audio.applescript:702:705: script error: Expected class name but found property. (-2741)
```

If I remove the whole section of google chrome, from the try to the end, the scripts works perfectly.
