### ISSUE TITLE
weather keep curl every 10s even I don't enable the widget

### ISSUE THREAD

**Issue by zhaochunqi** [Jean-Tinland/simple-bar#116]
https://twitter.com/igor_chubin/status/1361706329887375361

I found that the weather keep using curl to get weather information every 10s even I don't use it on my widget, this might be a problem for free service `wttr.in`.

**Comment by Jean-Tinland** [comment]
If you haven't enabled the weather widget in settings the get_data.sh is normally not doing the curl to `wttr.in`. Are you using the last version of simple-bar? There was a bug in this script until it was fixed last week, it may be related.

I'm planing on adding a little "cache" system preventing from doing a curl every 12 seconds when the weather widget is active.

**Comment by zhaochunqi** [comment]
oops, my bad.

Just pulled the latest code. Not doing `curl` when disabled weather.

Sorry for wasting your time, I'm closing this issue.
