### ISSUE TITLE
Google Chrome keeps opening

### ISSUE THREAD

**Issue by phlind** [Jean-Tinland/simple-bar#117]
When I activate the data widget, Google Chrome is opening. It keeps opening again, after I close it. I'm on macOS 11.2.3.

I commented out the section in `browser_audio.applescript` to fix it temporarily.

**Comment by devanlooches** [comment]
I am getting the same issue.

**Comment by Jean-Tinland** [comment]
Indeed, I'm also getting it, I'll try to figure something out soon.

**Comment by Aeysol** [comment]
I've created the pull request #125 to fix that.

**Comment by Jean-Tinland** [comment]
This is nice, that fix seems to work nice, thanks!

Feel free to reopen this issue if necessary.
