### ISSUE TITLE
Can you use it without Yabai?

### ISSUE THREAD

**Issue by meksrc** [Jean-Tinland/simple-bar#124]
Hey,

i wanted to ask If it’s possible to use this bar without using Yabai. And actually, what does Yabai have to do with the bar? Thanks :)

**Comment by Jean-Tinland** [comment]
Hi,

Unfortunately simple-bar can't work without yabai.

yabai is needed in order to display all existing workspaces & also to manipulate them (add, move, remove).

yabai is also necessary because with its stack or bsp mode it is reserving some space making the bar always accessible/visible.
