### ISSUE TITLE
All space widgets/names on main screen

### ISSUE THREAD

**Issue by christo-ph** [Jean-Tinland/simple-bar#126]
Hi.

As Yabai [does not support](https://github.com/koekeishiya/yabai/issues/136) the external bar on all monitors, I wonder if it is possible to have all spaces widget names on the main monitor [like described here](https://github.com/koekeishiya/yabai/issues/136#issuecomment-525480743).

Also the dash or pipe as the separator would be nice. Is there a setting for that?

**Comment by christo-ph** [comment]
It is possible to set the spacebar on all monitors with 

```
# yabai -m config external_bar [<main|all|off>:<top_padding>:<bottom_padding>]
  yabai -m config external_bar all:30:0
```

Nevertheless. To have all spaces shown on the main monitor would still be great.

**Comment by Jean-Tinland** [comment]
Hi!

Sorry for my late answer!
I can add an entry in settings that could do exactly what you want. I'll let you know here when it is ready (soon :) ).

**Comment by Jean-Tinland** [comment]
Hi again!

I added a setting "Display all spaces on all screens" in the "Spaces" tab.
I think this is exactly what you needed but feel free to le me know if I can improve this in any way! :)
