### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by brandonxoliver** [Jean-Tinland/simple-bar#128]
Not sure if this is the right channel to request icons. Please let me know if I should direct this elsewhere. 

Is it possible to add icon support for the following in a future release?
- DEVONthink 3
- Obsidian
- VimR, MacVim, or just plain old Vim
- Keyboard Maestro

Thanks!

**Comment by Jean-Tinland** [comment]
Hi, I just added icons for Obsidian, Vim (for app names VimR, MacVim, or Vim) and Keyboard Maestro icons.

I couldn't find a good DEVONthink 3 icon.

Let me know if these suits you, I can update them anytime. :)
