### ISSUE TITLE
Widget boxes gets scrambled

### ISSUE THREAD

**Issue by jonathanwalter** [Jean-Tinland/simple-bar#129]
_Sometimes_ (usually after waking from sleep) the widget boxes gets all scrambled.

![image](https://user-images.githubusercontent.com/1952613/117439324-ffd05100-af32-11eb-8ee2-12faa09c860c.png)

If I "Refresh All Widgets" from Übersicht they go back to "normal". Not a big deal, but annoying.

MacBook Pro 15" (2017)
macOS 11.3.1
Übersicht 1.6 (69)

**Comment by Jean-Tinland** [comment]
I added a `white-space: nowrap;` on the date widget. This should prevent this issue from now.

Let me know if you encounter any problem.
