### ISSUE TITLE
[Feature Request] Hide workspaces with 0 windows on them

### ISSUE THREAD

**Issue by spwx** [Jean-Tinland/simple-bar#131]
SIP must be disabled for Yabai to create and delete workspaces.

If SIP is enabled, the user must manually create multiple workspaces. These are always visible in the workspaces bar.

Is it possible to hide workspaces, which do not have any open windows?

**Comment by Jean-Tinland** [comment]
Hi!

I added setting "Hide empty spaces" in the "Spaces" tab.
<img width="582" alt="Screenshot 2021-05-22 at 15 49 12" src="https://user-images.githubusercontent.com/43068795/119229113-ac572900-bb16-11eb-83fe-0d8dd2ddd3bf.png">

This will hide all empty spaces except if you are on it.

Let me know if this suits you!

**Comment by spwx** [comment]
Just tested. AWESOME! This is literally perfect now! Thank you!
