### ISSUE TITLE
The weather widget uses the entire CPU in some circumstances.

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#132]
I have a M1 MacBook Air running Big Sur 11.3.1 (20E241) and have discovered an issue with the weather widget.

When the weather widget is enabled without specifying a location, many macOS processes seems to be eating the CPU.  
When this bug happens, in the "Energy" tab of the activity monitor, Übersicht has a score of >300.

This issue instantly disappear when either specifying a location, or disabling the weather widget.

Here is the macOS processes eating the CPU when the widget is active:
<img width="259" alt="Capture d’écran 2021-05-23 à 15 46 19" src="https://user-images.githubusercontent.com/17962248/119263233-7aa99500-bbde-11eb-9222-ecf6e24cc3bd.png">

I'm not using any other Übersicht widget, the location permission is indeed allowed to Übersicht.

**Comment by Jean-Tinland** [comment]
Hi!

I'll look into it, If it causes to much trouble I'm planing to disable the automatic geolocation and simply let the user manually set its location.

Thanks for the report!

**Comment by Jean-Tinland** [comment]
I tried to make the weather widget less aggressive when location cannot be determined. 

Let me know if the error still occur.

**Comment by HeySora** [comment]
@Jean-Tinland I've been testing this since a few days, and it seems to work flawlessly now!
I have the impression it takes more time to get the location, but that may be placebo.
Thank you for the fixes :)

**Comment by Jean-Tinland** [comment]
Indeed, instead of forcing simple-bar to refresh itself after getting user location, it is simply waiting for the next refresh 12 seconds later.

So it is only on launch or when the computer is waking that weather is not immediately displayed.

I think it is better like that. 

Thanks for testing this.

**Comment by HeySora** [comment]
I genuinely don't know how Übersicht refreshes work, but if you have e.g. 3 consecutive location attempts fail, would it be possible to prevent the weather widget to refresh until the network connection/status changes? (which is the most likely occasion where location will be available again)
or, after enough fails, maybe refresh the widget only each 5min for example, in order to avoid consuming battery?

**Comment by Jean-Tinland** [comment]
Indeed, I'll look into a more elegant way for handling this! For now it is working well. :)

I'm keeping this issue open as a reminder.

**Comment by Jean-Tinland** [comment]
The weather widget is now refreshing every 1 hour and is handled way differently than before. I think it is solving this issue. Feel free to reopen it or open a new one if you encounter any issue regarding this subject.
