### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by rmGFW** [Jean-Tinland/simple-bar#136]
add feature for rename space

**Comment by Jean-Tinland** [comment]
Yes I'd like to find an elegant way to implement this directly in simple-bar interface. In the mean time, you can add this function to you .bash_profile:
```sh
function rename_space() {
  yabai -m space $1 --label $2
  osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "simple-bar-spaces-jsx"'
}

# usage for renaming your third space
# yabai -m 3 --label "my custom space name"
```

I'll let you know when I come up with something. :)

**Comment by Jean-Tinland** [comment]
Hi!

All spaces can now be renamed by clicking on label with alt/option key pressed. :)
