### ISSUE TITLE
Major performance issues on Big Sur with simple-bar

### ISSUE THREAD

**Issue by issmirnov** [Jean-Tinland/simple-bar#141]
I'm running a 2019 16" MBP (2.4Ghz i9, 32gb RAM) with https://www.simple-bar.com/en/.

I have noticed major regressions after upgrading to Big Sur. The entire system slows to a crawl, to the point that even opening a new Google Chrome tab is unbearable slow and takes 5-8 seconds.

I'm running dual 2k 27" monitors, connected via a RX 570 through a Razer Core X Chroma GPU. Issue appears to be worse when the monitors are connected.

I triaged between https://github.com/felixhageloh/uebersicht/issues/450, https://github.com/koekeishiya/yabai/issues/892 and simple-bar and from what I and other uses can tell, the problem is coming from simple-bar. 

I notice that the Activity Monitor shows Ubersicht as using 80+ energy impact, with Chrome using about 90. This is surprising, as the bar has a notification event model rather than polling.

Could you take a look and see if there are other performance optimizations available?

**Comment by Jean-Tinland** [comment]
Hi!

That's weird as I haven't noticed anything on my part, I'm also running Big Sur on an older MBP (13" 2016) with a FHD external screen. Ubersicht's energy impact always stays under 10 and CPU usage vary between 1 & 5%. 

I'm normally switching to a 2019 16" MBM soon (in 1 or 2 weeks), I'll try to observe what could possibly provoke theses symptoms. I'm a little embarrassed that I doesn't run smoothly for everyone, I'll fo my best to resolve this. :)

Unfortunately It could be a lot of things.

Are you encountering any error if you open the Ubersicht console?
When encountering an error, simple-bar directly refresh itself until its works fine. 

You can also try to disable all data widget en see if one of them has an heavy impact on performances. Maybe some commands fetching particular data have a heavier cost on this MBP model.

I'll keep you updated as soon as I have news, thank for the report!

**Comment by Jean-Tinland** [comment]
Also, since you recently upgraded to Big Sur, have you seen [these additional steps](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup) after installing/upgrading yabai? Just in case :)

**Comment by Jean-Tinland** [comment]
Another thought, there was a bug in the weather widget causing an infinite refresh. This was fixed 4 days ago, are you up to date with the master branch?

**Comment by issmirnov** [comment]
Hi Jean,

Thank you - I updated to the latest refresh and the energy usage has fallen dramatically. Thank you!
