### ISSUE TITLE
Be able to change speed of window name moving

### ISSUE THREAD

**Issue by mTvare6** [Jean-Tinland/simple-bar#142]
The speed at which the window name moves is too slow, being able to [change](https://github.com/Jean-Tinland/simple-bar/blob/master/lib/components/process/window.jsx#L29) it using a option in UI would be very cool

**Comment by Jean-Tinland** [comment]
Hi, 

Indeed, it should be a user preference!

I will unify all the components using this sliding animation and add an entry in settings. I'll keep you posted. :)

**Comment by Jean-Tinland** [comment]
You'll find a `Sliding animation pace` in the "global" setting tab. The higher the `Sliding animation pace` value, the faster the texts slides. The default is 4 and it must be > 0.

Let me know if this suits you!

**Comment by mTvare6** [comment]
Looks good to me!
