### ISSUE TITLE
Duplicate calculation of pending changes

### ISSUE THREAD

**Issue by kpritam** [Jean-Tinland/simple-bar#146]
Even if you keep toggeling settings, number of pending changes gets increased.
Below image, I have just toggled setting (on/off) for 21 times and it shows 21 pending changes instead it should just say 1.

![image](https://user-images.githubusercontent.com/17781757/121464746-135b5580-c9d2-11eb-9299-09cf91e93eee.png)

**Comment by Jean-Tinland** [comment]
Hi, indeed, this "pending changes" functionality is a draft simply incrementing on each input changes. I'm planing on doing a real changes tests.

This is in the pipes, I'll let you know when this is fixed. :)

**Comment by Jean-Tinland** [comment]
I just updated the settings module in order to precisely calculate any real changes. These changes are now applied only on "Refresh simple-bar" button click.

Let me know if you encounter any issue with this update.
