### ISSUE TITLE
"simple-bar-data.jsx - Loading Data..." When Spotify is running without any song playing

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#148]
My Mac autostarts Spotify when logging in, and it (obviously) has no song going on. I'm not even sure if the UI is fully initialized at this point, since it's still minimized (which may be the cause of the issue).

When this situation happens, the right side of the bar (simple-bar-data.jsx) says "Loading data..." forever, then eventually says that something went wrong after a few minutes.

Doing [Cmd]-[Q] on Spotify, or playing a song, then reloading the widget works as expected.

**Comment by Jean-Tinland** [comment]
Hi, I though this issue was already solved! It may have been re introduced recently.

I'll investigate and let you know when I have more information about that, thanks!

**Comment by Jean-Tinland** [comment]
Let me know if you still encounter the issue, I may have solved it involuntarily (as I can reproduce it) with my latest commits.
