### ISSUE TITLE
[suggestion] separate space-bar background-color in theme.js

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#15]
Just a suggestion for my selfish benefit :) 

Btw nice touch with the new Specter and time filler!

I would like to see the space-bar background as a separate color in theme.js.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2527231/93155196-ae294b00-f744-11ea-8c4e-6706c516a390.png">

**Comment by Jean-Tinland** [comment]
I've added a separate entry for the background color:
```javascript
export const Theme = {
  main: '#1B222D',
  minor: '#39465E',
  accent: '#FFD484',
  red: '#E78482',
  green: '#8FC8BB',
  yellow: '#FFD484',
  blue: '#6DB3CE',
  magenta: '#AD82CB',
  cyan: '#7EDDDE',
  background: Theme.main,
  lightGrey: 'rgba(0, 0, 0, 0.1)',
  font: 'JetBrains Mono, monospace',
  lightShadow: '0 5px 10px rgba(0, 0, 0, 0.24)',
  mediumShadow: '0 8px 30px rgba(0, 0, 0, 0.24)',
  largeShadow: '0 30px 60px rgba(0, 0, 0, 0.24)',
  easing: 'cubic-bezier(0.4, 0, 0.2, 1)'
}
```

It's using the main color variable by default in order to maintain unchanged the other users configurations.

**Comment by MikoMagni** [comment]
Thank you  🔥
