### ISSUE TITLE
The weather widget sometimes reports a wrong temperature

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#150]
I tried reloading the whole widget as well as restarting Übersicht as well, nothing seems to change.

Widget preview:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/17962248/122364402-043c5080-cf5a-11eb-8e8b-aea552cef9d9.png">

When clicking on the widget:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/17962248/122364440-0e5e4f00-cf5a-11eb-82c6-2d0e6d0d8db3.png">

This happens when using "Lausanne" as a custom location.

**Comment by HeySora** [comment]
Small comment: I didn't notice your commit about custom locations made 2 hours ago, so I pulled again and retried:

The issue stays the same.

<img width="177" alt="image" src="https://user-images.githubusercontent.com/17962248/122367094-6bf39b00-cf5c-11eb-8276-e3f5c11a9476.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/17962248/122367123-71e97c00-cf5c-11eb-9d48-ca9e5b15d470.png">

**Comment by Jean-Tinland** [comment]
Hi! This should normally be fixed in my latest commit! :)
