### ISSUE TITLE
Suggestion: Make the process widget show its own monitor's windows

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#151]
If for example I'm on space 1 on my main monitor, and on space 2 on my second monitor, the process widget (when it displays all processes) should show its windows for its own monitor, instead of only the currently being used monitor.

Example of the process widget on my two monitors:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/17962248/122367774-0653de80-cf5d-11eb-9b81-bd47577946d6.png">
![image](https://user-images.githubusercontent.com/17962248/122367755-ff2cd080-cf5c-11eb-941c-7f9c3d4e0dd4.png)

The process widget on the second monitor still shows "Safari" as the current window, where I think it should show the TextEdit window (only its icon, since it's not focused)

The spaces widget seems to know that the second monitor is on space 8 in this case, even if it's unfocused, so I think it is possible to fetch the windows from that space?

**Comment by Jean-Tinland** [comment]
In order to make this work I will need to merge the space & the process widget, this is not a small change.

I think it is a great improvement so I'll try to make this work. :)

**Comment by Jean-Tinland** [comment]
I updated everything according to my previous message.

You will need to restart both `yabai` & `Übersicht` in order to make everything work again!

Now that I merged this 2 widgets, the process displays only the current space windows. The only limitation I was confronted to was that I can't know what window is focused on the non focused display, `yabai` is not giving the information. I may find a solution in a near future but I can't guaranty anything. Still this is better than before.

Let me know if you like it. :)

**Comment by HeySora** [comment]
I'll be able to test on Tuesday, I'll get you updated asap!!

Do I need more yabai signal events for this to work?

> The only limitation I was confronted to was that I can't know what window is focused on the non focused display,

Theorically..none? I think showing only its icon like an unfocused window is great, so knowing which monitor is currently focused is easier!

**Comment by Jean-Tinland** [comment]
> Do I need more yabai signal events for this to work?

On the contrary you can safely remove all the simple-bar related signals in your .yabairc, they are now automatically added by the bar.

> Theorically..none? I think showing only its icon like an unfocused window is great, so knowing which monitor is currently focused is easier!

Indeed haha but we could have wanted to show which was the last focused window that would be focused if you use yabai commands to focus a display again.

Anyway this is nice if this is matching your expectations. :)

**Comment by HeySora** [comment]
Hello @Jean-Tinland !

Sorry for the delay, I have not been able to properly test this before.
It works perfectly, thank you!! :D
