### ISSUE TITLE
The gap between labels and icons in the space component

### ISSUE THREAD

**Issue by terry182** [Jean-Tinland/simple-bar#156]
I find that the gap between labels and icons in the space component is a bit too wide. It does not seem like the screenshot, at least to me. 

(This happens on a MacBook Pro Retina 15-inch, Mid 2014 with macOS Big Sur.)

<img width="571" alt="Screenshot 2021-06-29 at 12 20 59 AM" src="https://user-images.githubusercontent.com/9360722/123670519-e29f6b00-d86f-11eb-8a5d-0cb286f0c429.png">

I changed the `margin-right` from `-4px` to `-20px` for class `.space__label`, and it looked better to me. I don't know if this is a good value so I didn't make a PR. 
<img width="502" alt="Screenshot 2021-06-29 at 12 24 23 AM" src="https://user-images.githubusercontent.com/9360722/123670977-5b9ec280-d870-11eb-8232-dc569eab3d6b.png">

**Comment by Jean-Tinland** [comment]
Indeed, this gap is more or less important depending on the fond used! I tested it with SF Mono and it was fine, my bad.

I'm looking for another solution. :)

Thanks for reporting it!

**Comment by terry182** [comment]
> Indeed, this gap is more or less important depending on the fond used! I tested it with SF Mono and it was fine, my bad.
> 
> I'm looking for another solution. :)
> 
> Thanks for reporting it!

I see. The font I used here is JetBrains Mono. Maybe we can set this value dynamically derived from the width of the glyph?

**Comment by Jean-Tinland** [comment]
I just fixed this issue! :)

Exactly, I set the input width to exactly the space name length + the "ch" CSS unit: 64b97af.
