### ISSUE TITLE
Weather continuously loads on second monitor

### ISSUE THREAD

**Issue by tkerr97** [Jean-Tinland/simple-bar#158]
With only one monitor, the weather widget works normally. But when there are two monitors (I haven't tested more than that), it doesn't load on the second monitor. It still shows the weather properly on the first monitor, however.

**Comment by Jean-Tinland** [comment]
I was able to reproduce the issue but I don't know what is causing it, I'll let you know when this is fixed!

**Comment by tkerr97** [comment]
Looks related to geolocation, setting my location fixes the issue

**Comment by Jean-Tinland** [comment]
Indeed, it seems so, I'll look into it soon :)

**Comment by albert-ying** [comment]
Just want to add that it doesn't load on the third monitor as well. Seems that it will only work on the main screen. Also while loading, everything else is stuck (aka no refreshing when changing space... etc). So I have to turn this widget off. Hope it will be fixed soon!

**Comment by Jean-Tinland** [comment]
I see, I couldn’t fix this for now, as stated before, you can manually set the location in order to avoid this problem.

I'll keep you posted when I find a solution.

**Comment by Jean-Tinland** [comment]
This should be fixed in my latest commit!
