### ISSUE TITLE
(Feature and Icons Request) Exceptions in Process widget as well as Spaces widget?

### ISSUE THREAD

**Issue by lclrc** [Jean-Tinland/simple-bar#160]
## Feature

Maybe some extraneous notification windows should be hidden in the process widget, like `Hammerspoon`. So exceptions in process widget?

## Icons

Icon for some apps:

* [Skim](https://skim-app.sourceforge.io/index.html)
* [Notability](https://www.gingerlabs.com)
* [Joplin](https://joplinapp.org)
* [Reeder](https://reederapp.com)

*Thanks in advance!*

**Comment by Jean-Tinland** [comment]
Hi! You can already add exclusion in spaces & process widgets:
![image](https://user-images.githubusercontent.com/43068795/125352336-6a51a300-e361-11eb-9799-c0e0c4cfb4a7.png)

You can either declare one by on app name or window title to excludes as a string separated by comma or simply by using regex syntax!

I'll add these for app icons soon. I'll let you know in this issue when it's done.

**Comment by Jean-Tinland** [comment]
Hi!

I added 4 new icons for theses apps. I only had a problem with the Skim app icon as I couldn't reproduce it so I added a generic "PDF app" icon that will also certainly serve for other similar app later. 

Let me know if this is fine and if everything is working, I'm not sure I had the correct app name when I associated these new icons to their app.

If not, can you give me the name display on the process widget:
![image](https://user-images.githubusercontent.com/43068795/126063372-193cc640-cc3a-4724-a681-d16a29dda768.png)

Thanks!

**Comment by lclrc** [comment]
> I added a generic "PDF app" icon that will also certainly serve for other similar app later.

It's a good idea!

By the way, The icon of Reeder is not work. 
This is its process name.
![Reeder](https://user-images.githubusercontent.com/23278764/126071008-3b572d95-7a52-4d6d-a0ca-fccc3e57e981.jpg)

And I modified `'Reeder 5': Reeder5Icon` to `'Reeder': Reeder5Icon`, then it works. Thanks!

**Comment by lclrc** [comment]
> Hi! You can already add exclusion in spaces & process widgets:
> ![image](https://user-images.githubusercontent.com/43068795/125352336-6a51a300-e361-11eb-9799-c0e0c4cfb4a7.png)
> 
> You can either declare one by on app name or window title to excludes as a string separated by comma or simply by using regex syntax!
> 
> I'll add these for app icons soon. I'll let you know in this issue when it's done.

About this, I still have some questions.
This is my simple-bar setting.
![simple-bar Setting](https://user-images.githubusercontent.com/23278764/126071478-c199eac1-3191-4a28-8c93-91bbb25691a9.jpg)
I use `AdamWagner/stackline` to display yabai stack program icon like this.
![Before](https://user-images.githubusercontent.com/23278764/126071453-d21e3d4c-88ac-40ea-968e-eab71950a008.jpg)
There are five process icons, but actually I just opened three windows, `Safari` `Alacritty` and `Joplin`. The exclusions are not worked in the process widget area?
This is output of `yabai -m query --windows`.
```
yabai -m query --windows
[{
        "id":3669,
        "pid":547,
        "app":"Hammerspoon",
        "title":"",
        "frame":{
                "x":0.0000,
                "y":0.0000,
                "w":1920.0000,
                "h":1080.0000
        },
        "level":1000,
        "role":"AXWindow",
        "subrole":"AXSystemDialog.Hammerspoon",
        "movable":1,
        "resizable":0,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":1,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":1,
        "border":0,
        "stack-index":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
},{
        "id":3668,
        "pid":547,
        "app":"Hammerspoon",
        "title":"",
        "frame":{
                "x":0.0000,
                "y":0.0000,
                "w":1920.0000,
                "h":1080.0000
        },
        "level":1000,
        "role":"AXWindow",
        "subrole":"AXSystemDialog.Hammerspoon",
        "movable":1,
        "resizable":0,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":1,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":1,
        "border":0,
        "stack-index":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
},{
        "id":1402,
        "pid":75939,
        "app":"Alacritty",
        "title":"❐ 0 ● 1 zsh",
        "frame":{
                "x":3.0000,
                "y":33.0000,
                "w":1914.0000,
                "h":1039.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":1,
        "visible":1,
        "focused":1,
        "split":"none",
        "floating":0,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":0,
        "border":1,
        "stack-index":2,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
},{
        "id":145,
        "pid":2217,
        "app":"Safari浏览器",
        "title":"(Feature and Icons Request) Exceptions in Process widget as well as Spaces widget? · Issue #160 · Jean-Tinland/simple-bar",
        "frame":{
                "x":3.0000,
                "y":33.0000,
                "w":1914.0000,
                "h":1039.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":0,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":0,
        "border":1,
        "stack-index":1,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
},{
        "id":3546,
        "pid":46924,
        "app":"Joplin",
        "title":"Joplin",
        "frame":{
                "x":3.0000,
                "y":33.0000,
                "w":1181.0000,
                "h":1039.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":0,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":1,
        "border":1,
        "stack-index":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}]
```
There are two extra processes named `Hammerspoon`, they are stackline icons which I don't want see in the process widget of simple-bar. What I need to do?

My temporary idea is to modify file `simple-bar/lib/components/process/window.jsx`.
Change this line `if (minimized === 1 || (displayOnlyCurrent && focused !== 1)) return null` to `if (app === 'Hammerspoon' || minimized === 1 || (displayOnlyCurrent && focused !== 1)) return null`.
And then these two extra icons in process widget disappear. Like this:
![After](https://user-images.githubusercontent.com/23278764/126072171-23b3235b-77ed-4b6a-bedd-1d12ead4ca8d.jpg)

**Comment by Jean-Tinland** [comment]
My bad, I was sure I already implemented the same behaviour for spaces and processes!

If you pull the latest commit, everything should work as intended! :)

**Comment by lclrc** [comment]
YES! It worked! Thanks and I will close the issue! :)
