### ISSUE TITLE
simple-bar-spaces crashes if the folder is not called "simple-bar".

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#161]
If the Übersicht widget folder is not called `simple-bar`, simple-bar-spaces crashes early.

It's due to this line, expecting the folder to be called `simple-bar`:
https://github.com/Jean-Tinland/simple-bar/blob/1f0be505fea98bb5c88384738e1a49d6a797114d/spaces.jsx#L20

If this can't be fixed, I think a warning in the README would be useful for new people :)

**Comment by Jean-Tinland** [comment]
Indeed, I'll amend the readme with this note. I hadn't thought about custom installs!

**Comment by HeySora** [comment]
It's okay! :)  
The only reason I had a different folder name was for comparing master with the version I was running before, in order to give feedback to some issues, so I had to rename the folder.

**Comment by Jean-Tinland** [comment]
I just added a warning about this in the "Installation" section of the REAME.

I also wanted to thank you for your sponsorship, it really means a lot and encourage me to keep improving & fixing things here!
