### ISSUE TITLE
VPN widget spinning and spinning

### ISSUE THREAD

**Issue by d-miketa** [Jean-Tinland/simple-bar#163]
The Viscosity widget has stopped working at some (recent) point. There's a looped spinning animation on red background and it won't react to any input:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/320321/125462468-8a17e74e-e5ed-4506-bf93-529496132bc1.png">

The debug console hasn't been very helpful:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/320321/125462693-fca04561-a7b8-478c-912c-68327f58d91c.png">

**Comment by Jean-Tinland** [comment]
Hi, this should be fixed now ! :)

**Comment by d-miketa** [comment]
Thanks – it's working now but a bit less responsively than it used to. There's a long lag between clicking on the button and seeing it change its state. But the effect on the VPN connection is immediate.

**Comment by Jean-Tinland** [comment]
I see, it certainly have to do with my latest optimisations (that aren't always optimisations it seems).

I'll look into it because I have been observing the same behaviour on the battery widget which is getting too much time to refresh when I click on it and activate `caffeinate`!

Thank you for reporting it :)

**Comment by Jean-Tinland** [comment]
Aaand it should be fixed too now!

**Comment by d-miketa** [comment]
It fixed the battery issue for sure :) , but VPN behaviour's unchanged.

**Comment by Jean-Tinland** [comment]
Indeed, I think I just improved it a bit more but you'll tell me on your end if this is better. I'm testing with some free vpn config that are really slow to authenticate.

**Comment by d-miketa** [comment]
It's much better, thank you! There's still like 2-4 seconds of lag between hitting the button and changing state. I think it used to show a "connecting" state and I can't see that anymore; I wonder if its absence isn't adding to the "feeling" of non-responsiveness.

**Comment by Jean-Tinland** [comment]
I see! I'll give another look at that soon :)

**Comment by d-miketa** [comment]
Not sure why but it's working 100% now – if that was your doing, thank you! :)
