### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by basbebe** [Jean-Tinland/simple-bar#164]
Hi!

Would it be possible to add some of the following icons?

- [Signal](https://signal.org/)
- [Zulip](https://zulip.com/)
- [Element](https://element.io/)
- [Kakoune](https://kakoune.org/)
- [KeePassXC](https://keepassxc.org/)
- [MailMate](https://freron.com/)
- [mpv](https://mpv.io/)
- [Tor Browser](https://www.torproject.org/)
- [Skim](https://skim-app.sourceforge.io/)
- [zathura](https://pwmt.org/projects/zathura/) (has no icon though – maybe a 'generic' pdf icon?)
- [moneymoney](https://moneymoney-app.com/)
- [GrandTotal](https://www.mediaatelier.com/GrandTotal7/)
- [Receipts](https://www.receipts-app.com/)

Thanks!

**Comment by Jean-Tinland** [comment]
Hi!

It is certainly possible, but that's a lot of icons so I will add them progressively :)

**Comment by basbebe** [comment]
I wouldn't have expected you to add them all at once, so thanks a lot already!

**Comment by kvndrsslr** [comment]
What is the process for adding these icons? Do you manually create them using some vector art application or is there an automated way? I would love to contribute to this.

**Comment by kvndrsslr** [comment]
I'll try this out for sure at the weekend, thanks for the instructions!

**Comment by Jean-Tinland** [comment]
It seems that everything is tracked in #189 , I'm closing this. :)
