### ISSUE TITLE
add ability to remove shadow only for bar

### ISSUE THREAD

**Issue by basbebe** [Jean-Tinland/simple-bar#166]
yabai allows to remove the shadow for all (or all managed) windows.
simple-bar does not respect this setting and applies the shadow to bar icons _and_ the bar itself or neither.

setting
```js
  lightShadow: '0 0 0 rgba(0, 0, 0, 0)',
```
will remove the shadow from the bar _and_ from the buttons.

It wil also add some weird effects in my case:
![Screenshot 2021-07-18 at 12 03 21](https://user-images.githubusercontent.com/7083188/126063171-214d73d0-48dd-44f7-8748-df034888ccd9.png)

So it would be great to have a setting to enable / disable just the bar's shadow or to respect yabai's setting.

**Comment by Jean-Tinland** [comment]
Indeed, I can't easily sync the bar shadow directly with yabai so I will add a setting in simple-bar allowing to disable its shadow.

This graphic glitch may disappear after making the said change.

**Comment by basbebe** [comment]
`yabai -m config window_shadow` will return the current configuration.

```fish
❯ yabai -m config window_shadow
float
```

And I guess this shouldn't change too often, so checking it on initialisation could suffice

**Comment by Jean-Tinland** [comment]
This is now implemented, thank you for your input! :)
