### ISSUE TITLE
add toggle for dark mode

### ISSUE THREAD

**Issue by basbebe** [Jean-Tinland/simple-bar#167]
Clicking the clock already toggles notifications.
But I guess it would also be useful if it toggled Dark Mode.

Or if there was a dedicated toggle to switch between Light Mode, Dark Mode and Automatic.

On the other hand many people probably already either have it fixed or have some other way to manage it (DarkModeBuddy, scripts, hotkeys) so maybe there is no need at all.

**Comment by Jean-Tinland** [comment]
I'm thinking of a keyboard shortcut toggling auto, dark, light modes:

First click on simple-bar, then press `cmd + t` and repeat the operation any time needed in order to loop over the 3 possible modes.

What do you think?

**Comment by basbebe** [comment]
UX-wise I think it would then make sense to have a 'state' where simple-bar is selected and report that.
e.g. invert the window title in the bar when the user clicks on a blank space in the bar.
That way, settings (<kbd>⌘</kbd>+<kbd>,</kbd>) could also be triggered no matter where the bar is being clicked.

**Comment by Jean-Tinland** [comment]
I agree, I need to find an elegant way that always work regarding the user's configuration because process/window name can be hidden in settings.

As for now I added the <kbd>⌘ + t</kbd> shortchut allowing to loop through the 3 themes.

**Comment by basbebe** [comment]
nice!

Actually I thought about toggling dark system-wide (which I think this would not do, right?)

**Comment by Jean-Tinland** [comment]
I added a system wide toggle using the same shortcut! Let me know if this is working well :)
