### ISSUE TITLE
Fullscreen app does not appear anymore as a yellow space

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#168]
Fullscreened apps used to appear as a space with a yellow-ish background color. It is not the case anymore as of latest master.

**Comment by Jean-Tinland** [comment]
I absolutely don’t know why I removed this functionality!

Sorry for that, it should be OK now. :)

**Comment by HeySora** [comment]
Thank you, it works as expected now :)

Do not worry, mistakes happen and it was not super important! Thank you for your speed :D

**Comment by HeySora** [comment]
Oops, another thing:

An app taking the whole space via yabai (alt-d and alt-f, with a default `skhdrc`) does not have a yellow icon as it did before. 😉

**Comment by Jean-Tinland** [comment]
Fixed! I must have thought I was the only one using this. :)
