### ISSUE TITLE
Terminal space icon is hard to see on low resolution screens

### ISSUE THREAD

**Issue by jamieweavis** [Jean-Tinland/simple-bar#17]
Hey Jean,

The current terminal space icon is quite difficult to recognise on lower resolution external screens, for example (in 1080p):
![Screenshot 2020-09-15 at 08 23 06](https://user-images.githubusercontent.com/8133259/93178968-efadfc00-f72c-11ea-888f-64bfaa5258d7.png)![Screenshot 2020-09-15 at 08 52 22](https://user-images.githubusercontent.com/8133259/93181780-d018d280-f730-11ea-874d-f78a624c8f7f.png)

I tried a similar prompt icon without the surrounding box and it looks slightly better, but maybe there are better options?
![Screenshot 2020-09-15 at 08 34 55](https://user-images.githubusercontent.com/8133259/93180563-40265900-f72f-11ea-9cc7-f5c4341bcd10.png)![Screenshot 2020-09-15 at 08 40 25](https://user-images.githubusercontent.com/8133259/93180573-44527680-f72f-11ea-8b61-285d440af1af.png)

Other suggestions:
- Single chevron (without the underscore)
- Dollar sign

**Comment by Jean-Tinland** [comment]
Hi,

Indeed, I wasn't satisfied either with this icon. I like your first proposal (image).

**Comment by jamieweavis** [comment]
Alright, I'll submit a PR this later afternoon 👍
