### ISSUE TITLE
[Question] Animation slow when moving between spaces

### ISSUE THREAD

**Issue by c0deForLife** [Jean-Tinland/simple-bar#173]
First of all thank you for creating simple bar, its everything i needed, except i cannot figure out how to get rid of animation lag when moving spaces.
Say i want to move from space 1 to space 8, i press the shortcut keys, and the windows change, followed by a second - two seconds of delay and then the active space indicator changes from space 1 to space 8.

I tried searching and came across your recommendation to disable animations in custom-styles.js, but it has not helped. 
Should the space change be reflected immediately in bar when jumping between spaces ?

**Comment by Jean-Tinland** [comment]
Hi!

I'm really glad you like simple-bar!

There is indeed a delay on space change. There is unfortunately not a lot of thing you can do about it: the higher is your setup the lower the delay will be. On a 16" 2019 MBP 16GB there is almost no delay for example.
Also, if you have a lot of process running, background tasks, etc... it can increase the delay even more.

You can try to switch the shell used by simple-bar in order to reduce this lag.
![image](https://user-images.githubusercontent.com/43068795/127609103-5eccca1a-c1bb-46ee-a4e3-8416faa8ea39.png)

**Comment by devnoname120** [comment]
@Jean-Tinland Even with `dash` it's still super slow (eyeball measurement: 0.5 → 1s[1]).

Is there a config change that could help speed up things?

I already disabled pretty much every widget. Here is how my complete bar looks like right now:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/2824100/185707544-c590bf99-04bf-4e0a-9314-9a37305305c1.png">




[1] MacBook Air M1 (2021) running macOS Monterey 12.4

**Comment by kabeero** [comment]
Hi, I thought I had a similar issue but it got significantly better (2-3x faster) when I did the following:

1. Run [simple-bar-server](https://github.com/Jean-Tinland/simple-bar-server)
    - e.g: `npm install ; npm run dev`

2. Ensure `simple-bar` is setup to use port `7777` for the websocket
    - This is the default setting, if you changed it, make sure your `.simplebarrc` file's `serverSocketPort` is `7777` exactly (no quotes)

3. Setup `yabai` on events to `curl` to `simple-bar-server` with `yabai -m signal *` ([docs](https://www.jeantinland.com/toolbox/simple-bar-server/documentation/yabai/))

4. Make sure SIP is disabled and you have loaded scripting add-ons
   - `csrutil status ; sudo yabai --load-sa`
   - If you want `yabai` to auto load SA you need to set up the `/etc/sudoers.d/yabai` file with checksum and update it every time `yabai` is upgraded ([docs](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition))
   - On newer macOS, you can test yabai is working with SA, try to send your terminal to another space: `yabai -m window --space 1 --focus`

Before these changes, I would say it took 3-4 seconds for simple-bar to update on events. Now, it is almost exactly 1 second. I didn't notice any change before when trying `sh` vs `bash` vs `dash`

**Comment by devnoname120** [comment]
@kabeero 1 second is still pretty slow (that's what we are complaining about). I think you may have had a different issue than us
