### ISSUE TITLE
Unclear words on sound widget

### ISSUE THREAD

**Issue by yanzhang0219** [Jean-Tinland/simple-bar#174]
After checking "No colors in date", the sound widget turns gray, and no matter how much volume I turn up, it stays gray all the time. It is very unclear. Thank you.

<img width="140" alt="image" src="https://user-images.githubusercontent.com/11582667/127568019-13aff2ba-f991-4eec-8f8e-8fa7fcd3aaec.png">

Thank you.

UPDATE:
I fixed it in this PR https://github.com/Jean-Tinland/simple-bar/pull/175. Please review it.

**Comment by Jean-Tinland** [comment]
Hi, I fixed it on my part as it was an error that slipped in when I updated the sound & mic widgets behaviour, thank you for reporting it!

**Comment by yanzhang0219** [comment]
Okay. Thank you. Feel free to close my PR.
