### ISSUE TITLE
Rename custom-styles.css to custom-styles.css.template and add it to .gitignore

### ISSUE THREAD

**Issue by kvndrsslr** [Jean-Tinland/simple-bar#180]
This would make it easier to contribute without polluting PRs with custom styles.
If there is an alternative git workflow that doesn't need this change please educate me :)

**Comment by Jean-Tinland** [comment]
Hi, I was thinking about moving the custom styles in settings. Doing so, it will become a user pref automatically excluded while updating the repo.
