### ISSUE TITLE
Theme Styling Issue 

### ISSUE THREAD

**Issue by Sylenss** [Jean-Tinland/simple-bar#186]
GoodMorning Jean,

This simple-bar is by far amazing!! Thank you for creating this! 

But I seem to be running into an issue with the styling I'm trying to achieve when setting up my custom scheme colors  

## I like the settings I have here 
<img width="1920" alt="Screen Shot 2021-08-12 at 3 57 44 AM" src="https://user-images.githubusercontent.com/45975952/129160282-13f23bf6-f399-48e4-a514-19a69e1d2340.png">
<img width="1919" alt="Screen Shot 2021-08-12 at 4 02 02 AM" src="https://user-images.githubusercontent.com/45975952/129160710-504a4c53-3390-46f9-a410-7f4eb81343b7.png">

## My problem arises when I change the settings to something like this 

<img width="1919" alt="Screen Shot 2021-08-12 at 4 05 50 AM" src="https://user-images.githubusercontent.com/45975952/129162888-80a5996e-c5cc-40bd-8866-745364e51fdf.png">

### What im trying to achieve is this color workspace button bg 
<img width="92" alt="Screen Shot 2021-08-12 at 4 20 34 AM" src="https://user-images.githubusercontent.com/45975952/129163787-0ffd9b45-d3bb-4c2b-b017-48695944df6b.png">

### Along with this spaces and the time and calendar colors scheme like this 
<img width="1920" alt="Screen Shot 2021-08-12 at 4 22 36 AM" src="https://user-images.githubusercontent.com/45975952/129164203-a91e9adc-eed2-4881-abc2-6daebc2c88d4.png">

* Below you would find the settings to the first screenshots 

```javascript 
export const theme = {
  name: 'CodingInSylens',
  kind: 'dark',
  main: '#1B2229',    // background
  mainAlt: '#ff0000', // confused about this settings
  minor: '#1b2229',   // workspace buttons
  red: '#cc241d',
  green: '#98971a',
  yellow: '#d79921',
  orange: '#d65d0e',
  blue: '#458588',
  magenta: '#b16286',
  cyan: '#689d6a',
  black: '#9b863e',   // tips box fg
  white: '#1b2229',   // tips box bg
  foreground: '#9b863e', // window title font & active workspace bg
  transparentDark: 'rgba(0, 0, 0, 0.05)',
  defaultFont: 'JetBrains Mono, monospace',
  barHeight: '28px',
  barRadius: '3px',
  barInnerMargin: '3px',
  itemRadius: '2px',
  itemInnerMargin: '3px 7px',
  itemOuterMargin: '0 0 0 5px',
  hoverRing: '0 0 0 2px rgba(255, 255, 255, 0.75)',
  focusRing: '0 0 0 2px rgb(255, 255, 255)',
  lightShadow: '0 5px 10px rgba(0, 0, 0, 0.24)',
  transitionEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  clickEffect: 'rgba(255, 255, 255, H0.3)'
}
```
* Here is the settings that im having a problem with the settings I'm trying to but with the spaces background of the first screen shot along side the calendar and time buttons in the first screenshot above 

```javascript 
export const theme = {
  name: 'CodingInSylens',
  kind: 'dark',
  main: '#1B2229',    // background
  mainAlt: '#ff0000', // confused
  minor: '#9b863e',   // workspace buttons
  red: '#cc241d',
  green: '#98971a',
  yellow: '#d79921',
  orange: '#d65d0e',
  blue: '#458588',
  magenta: '#b16286',
  cyan: '#689d6a',
  black: '#9b836e',   // tips box bg
  white: '#1b2229',   // tips box fg
  foreground: '#1b2229', // window title font & active workspace bg
  transparentDark: 'rgba(0, 0, 0, 0.05)',
  defaultFont: 'JetBrains Mono, monospace',
  barHeight: '28px',
  barRadius: '3px',
  barInnerMargin: '3px',
  itemRadius: '2px',
  itemInnerMargin: '3px 7px',
  itemOuterMargin: '0 0 0 5px',
  hoverRing: '0 0 0 2px rgba(255, 255, 255, 0.75)',
  focusRing: '0 0 0 2px rgb(255, 255, 255)',
  lightShadow: '0 5px 10px rgba(0, 0, 0, 0.24)',
  transitionEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
  clickEffect: 'rgba(255, 255, 255, 0.3)'
}
```

**Comment by Sylenss** [comment]
Also, may I ask if I can share my theme, when I resolve this issue?

**Comment by Jean-Tinland** [comment]
Hi!

I'll look into it soon :)

Yeah of course, I'd be glad to add you theme to the already available ones.

**Comment by Sylenss** [comment]
Sounds good, and Thank you for getting back to me! I can’t wait to tackle this problem. 

& Really!! Thank you, this means a lot!

**Comment by Jean-Tinland** [comment]
Hi!

If I correctly understood your problem, my latest commit should allow you to achieve what you wanted.

You can keep your theme as is (the first version you shared) and apply this new setting:
![Screenshot 2021-08-20 at 19 21 41](https://user-images.githubusercontent.com/43068795/130271265-7ca72f90-4b48-4793-b9da-1ab970676401.jpg)

By also toggling this setting `No colors in data`, I think you'll have all you need.

Let me know if this helps you!

**Comment by Sylenss** [comment]
GoodDay Jean, 

Sorry to get back to you at this time frame, but the bar is not updating any information I give it in the settings file.

I currently have the settings of the 

```javascript
global: {
    theme: 'auto',
    floatingBar: false,
    noBarBg: false,
    noColorInData: true,
    bottomBar: false,
    inlineSpacesOptions: true,
    disableNotifications: false,
    backgroundColorAsForeground: true,
    font: 'Monolisa',
    fontSize: '11px',
    yabaiPath: '/usr/local/bin/yabai',
    shell: 'sh',
    slidingAnimationPace: 4,
    externalConfigFile: false
  },
  themes: {
    lightTheme: 'NightShiftLight',
    darkTheme: 'CodingInSylens'
  },
  widgets: {
    processWidget: false,
    weatherWidget: false,
    batteryWidget: true,
    wifiWidget: false,
    vpnWidget: false,
    zoomWidget: false,
    soundWidget: true,
    micWidget: false,
    dateWidget: true,
    timeWidget: true,
    keyboardWidget: false,
    spotifyWidget: false,
    musicWidget: false,
    mpdWidget: false,
    browserTrackWidget: false
  },
```

The bar is at a constant color shown here 

### Also any idea on how I can get the bar to not have the application overlap it?
<img width="1680" alt="Screen Shot 2021-08-21 at 6 44 45 AM" src="https://user-images.githubusercontent.com/45975952/130319330-86273135-483c-4034-8c60-d8dfff183105.png">

## My yabai setting currently have the following 

- yabai -m config layout                           bsp
- yabai -m config top_padding                 13
- yabai -m config bottom_padding          13
- yabai -m config left_padding                 13
- yabai -m config right_padding               13
- yabai -m config window_gap                  06

**Comment by Jean-Tinland** [comment]
Hi!

Using the first version of your theme and these 2 settings activated (No color in data + Use background color as foreground) I'm getting this result:
![Screenshot 2021-08-21 at 14 49 39](https://user-images.githubusercontent.com/43068795/130322449-9cc4ab84-fc24-4a39-8dbb-eef666cda740.jpg)

Is it what you expected?

On the other matter, in order to prevent the windows overlap, you'll need to add this line in your `.yabairc` file:

```sh
yabai -m config external_bar                 all:28:0
```

Where 28 is the default simple-bar's height. 0 is the bottom bar height value that you would need to use if you had activated "Bottom bar" in settings.

**Comment by Sylenss** [comment]
Hey, Jean 

- I masked the workspace together with the whole bar to help with the look im trying to achieve, most of these settings here in the simple bar below are from the **second settings** listed not the first, but the border does give it some life so ill take that but this is the look im trying to achieve. here's the entirety of the look im trying to achieve, when you click the option for  (No color in data + Use background color as foreground + display only process name ) the border around the application section should be gone, resulting in a clean look. 

![Group 2](https://user-images.githubusercontent.com/45975952/130325530-cb10b8f0-4b5f-4f3c-b072-6df819a0273b.png)

Also thank you for that yabai setting it helped prevent the window from overlapping!

**Comment by Sylenss** [comment]
Good day jean, I know you’re busy, just wanted to know if there is an update on the styling?

**Comment by Sylenss** [comment]
hey, Jean Ive made a few more changes to the settings and I am happy with the settings below, sorry if I overwhelmed you with confusion and thank you so much for your help and creating this elegant bar, im not sure how to push these changes to the repo, so ill post it here! 

```javascript 
export const theme = {
    name: 'CodingInSylens',
    kind: 'dark',
    main: '#1B2229',    // background
    mainAlt: '#ff0000', // confused about this settings
    minor: '#1b2229',   // workspace buttons
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    orange: '#d65d0e',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    black: '#9b863e',   // tips box fg
    white: '#1b2229',   // tips box bg
    foreground: '#9b863e', // window title font & active workspace bg
    transparentDark: 'rgba(0, 0, 0, 0.05)',
    defaultFont: 'MonoLisa',
    barHeight: '28px',
    barRadius: '3px',
    barInnerMargin: '3px',
    itemRadius: '2px',
    itemInnerMargin: '3px 7px',
    itemOuterMargin: '0 0 0 5px',
    hoverRing: '0 0 0 2px rgba(155, 134, 62, 0.75)',
    focusRing: '0 0 0 2px rgb(155, 134, 62)',
    lightShadow: '0 5px 10px rgba(0, 0, 0, 0.24)',
    transitionEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    clickEffect: 'rgba(155, 134, 62, H0.3)'
  }
  ```

**Comment by Jean-Tinland** [comment]
Hi @Sylenss sorry for my late response, I'm glad it worked out, your theme looks really nice, I just added it in my latest commit.

Thank you for your contribution!

**Comment by Sylenss** [comment]
No worries, that's for getting back to me, & thank you for creating this elegant bar, im also glad you enjoy my theme 😄
