### ISSUE TITLE
Icon for Tower Git Client 

### ISSUE THREAD

**Issue by SijanC147** [Jean-Tinland/simple-bar#188]
[Tower](https://www.git-tower.com/mac) is a git client, not sure if you can find an svg icon for it, but maybe since it's a git client we could use a generic git icon? 

Edit: Maybe the right side of [this](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhn718fnTCsuXhwwcITtFsX1AI4knG1NWwWg&usqp=CAU), taken from their website

Thanks

**Comment by Jean-Tinland** [comment]
Hi, this request is now tracked in #189 :)
