### ISSUE TITLE
Add option to set different text size for different displays

### ISSUE THREAD

**Issue by rosenpin** [Jean-Tinland/simple-bar#193]
I think it would be great to have an option to set a different text size for different displays!  
I'm using a macbook air 13" and sometimes plug it in to a 30" monitor at my desk. When using it as a laptop 11px font is perfect, but connected to the high res 30" screen it's unreadable, so 13px/14px is my go to.

Could be very cool if it could be changed automatically.  
I think it's very feasible too, since yabai has the "display_added" signal already. All we have to do is add an option to set the desired font size in the UI and apply it accordingly.  
I think this UI could work and be pretty easy to implement:

### UI START
[ display UUID ] - [ font size ]
[ display UUID ] - [ font size ]
\+ button (to configuration)
### UI END

     
The display UUID can be fetched using `yabai -m query --displays | grep uuid`  
and could be extracted using `yabai -m query --displays | grep uuid | grep -o '[A-Z0-9].*[A-Z0-9]' `

**Comment by Jean-Tinland** [comment]
Hi!

Have you try using the `inch` or `cm` units instead of `px`? I can't try it and I'm curious about the result!

**Comment by rosenpin** [comment]
Yeah that's an interesting idea I'll try it out later today when I'm home!

**Comment by rosenpin** [comment]
I ended up using `1vh` and it works great.  



Be careful though not to set it to anything too big, because the font size also affects the settings, and if it's a bit too much you won't be able to change the settings back from the GUI.  
If you run into this open the Ubershicht debug console and modify the localStorage config json manually

**Comment by Jean-Tinland** [comment]
Great! I'm glad this work this way I prefer a simple CSS solution rather than implementing a more complex system :)

**Comment by rosenpin** [comment]
Yeah I'm totally with you, it's much better when possible.  
Maybe consider adding a note next to the font size letting users know it's something they should consider (using vh/%/inch/cm instead of px)
