### ISSUE TITLE
Feature/monitoring + Icon

### ISSUE THREAD

**Issue by kocierik** [Jean-Tinland/simple-bar#204]
Can you add a cpu monitoring? like iGlance?

<img width="75" alt="Screenshot 2021-08-28 at 13 59 42" src="https://user-images.githubusercontent.com/41591336/131217114-4af6c50b-715e-417f-b6d3-e14564379d79.png">

Can I add a pc temperature in any way?

**Comment by Jean-Tinland** [comment]
Hi, I need to look into it but it look feasible. I'll keep you posted here!

**Comment by Jean-Tinland** [comment]
About your last question, you could install [this utility](https://github.com/lavoiesl/osx-cpu-temp) (follow the instruction of the repo's readme).

After installing it you would need to create a custom widget that would look like that:
![image](https://user-images.githubusercontent.com/43068795/131959736-6a3df4c4-b7fd-49f8-a52f-5f620c562a99.png)

You may need to adjust the command path depending on how you installed this utility.

Result:
![image](https://user-images.githubusercontent.com/43068795/131959752-45aaf875-bfca-4a87-b3dc-71d14736524a.png)

I just added a thermostat icon so you can set it as your new custom widget icon.

Let me know if you succeed.

**Comment by kocierik** [comment]
I can't interact with the menu-bar... I've  activated the interaction in the Ubersicht Preferences but still does not work, so I can't access to the settings (cmd + ,). 

It's seem like any settings doesn't work. 

Maybe I need to reinstall Ubersicht? (I tried to reinstall simple-bar)

**Comment by Jean-Tinland** [comment]
This is weird, maybe reinstalling Übersicht is the first step.

Otherwise, have you check if your widgets are on the Übersicht foreground?

You can find that information here:
![Screenshot 2021-09-06 at 10 08 02](https://user-images.githubusercontent.com/43068795/132186503-4b1e4456-5ac3-4b2b-b578-704f63734d3c.jpg)

If the action is "Send to foreground" you can click it. simple-bar should become interactive after that.

**Comment by kocierik** [comment]
Thank you now work! I didn't check the Übersicht foreground!
<img width="593" alt="Screenshot 2021-09-06 at 12 32 34" src="https://user-images.githubusercontent.com/41591336/132204276-fd1fd9c7-0d6a-410c-9715-0f2fc1a14111.png">
