### ISSUE TITLE
Adding link to repo setting

### ISSUE THREAD

**Issue by toyboot4e** [Jean-Tinland/simple-bar#209]
Hi, `simple-bar` is making my life better!

I suggest editing repository details and adding link to https://www.simple-bar.com/en/

<img width="253" alt="link-here" src="https://user-images.githubusercontent.com/47905926/131846252-f0713da4-7488-4bd7-ac6d-c447a5ba02f4.png">

so that users easily access the awesome website. Thank you.

**Comment by Jean-Tinland** [comment]
I'm pleased that you like it :)

Great idea and now done, thanks!
