### ISSUE TITLE
I accidentally increased the font size a little more than it should've been

### ISSUE THREAD

**Issue by KeremArslan1** [Jean-Tinland/simple-bar#210]
Hello everyone, While I was customizing the Simple-bar I thought "hmm the bar looks a little bit small, let's increase the font size" I increased the font size to 20, and now the settings menu does not fit the screen and now I'm no longer able to change the settings of it.
I tried deleting the files of simple-bar and re-installing them to /users/keremarslan/Library/Application Support/Übersicht/widgets but I don't think the config file is in that path because it looks exactly the same and the settings did not change. What is the path of the config file?
![Screenshot 2021-09-03 at 20 28 48](https://user-images.githubusercontent.com/75943060/132045603-d0a3ff6b-e41d-4f3c-91e1-d54d84f2c050.png)

**Comment by Jean-Tinland** [comment]
Oooops, I see what happened here!

I'm fixing this tomorrow with an internal scrollbar in settings so the bottom button would always be visible. :)

**Comment by KeremArslan1** [comment]
> Oooops, I see what happened here!
> 
> I'm fixing this tomorrow with an internal scrollbar in settings so the bottom button would always be visible. :)

I would really appreciate that, thank you so much. Btw Simple-bar looks so cool.

**Comment by Jean-Tinland** [comment]
Everything should be better now!

Thanks! :)
