### ISSUE TITLE
Spotify running detection conflicts with Elgato Streamdeck

### ISSUE THREAD

**Issue by s00500** [Jean-Tinland/simple-bar#213]
I had the issue that I could not quit Spotify. After debugging a little I found that the Streamdeck softwares spotify integration launches a process that is exactly the same name as Spotify (at least when checked via applescript)

This meas simple bar would still believe Spotify is running while it was not, and therefore restart it when using applescript to ask for the current track info

To fix this I changed the code for the detection to this (in spotify.jsx)

```
    const isRunning = await run(
      `ps aux | grep '[S]potify Helper'`
      )
    if (cleanupOutput(isRunning).length == 0) {
      setLoading(false)
      setState({
        playerState: "",
        trackName: "",
        artistName: ""
      })
      return
    }
```

What do you think ? Shall I add a PR ?

**Comment by Jean-Tinland** [comment]
Hi, a PR is welcome, I'll test it and merge it as soon as I can :)
