### ISSUE TITLE
Window titles containing "inf" get displayed incorrectly

### ISSUE THREAD

**Issue by jming422** [Jean-Tinland/simple-bar#217]
## Expected behavior

Window titles are displayed by simple-bar's process widget with the same text as the window's actual title

## Actual behavior

Instances of the case-sensitive string `inf` are replaced with `0` in window titles. I believe this is because of the `sed` invocation here: https://github.com/Jean-Tinland/simple-bar/blob/e35a2a1bf11706ca5af3fcb34a36441dcd498a3c/lib/scripts/init.sh#L4

It looks like that was done on purpose, but I don't know why; it doesn't seem to do anything except edit window titles on my system:
```
﻿﻿$ yabai -m query --windows | grep inf
        "title":"Misinformation Definition & Meaning | Dictionary.com",
```

Would it be possible to remove that replacement of `inf` to `0`? Or is it used to support another use case?

## Screenshot

<img width="903" alt="Screen Shot 2021-09-10 at 2 23 09 PM" src="https://user-images.githubusercontent.com/8932155/132919685-851fd306-b3fb-4cc3-a884-f042c7848621.png">

**Comment by Jean-Tinland** [comment]
Hi! This was a quick fix solving the JSON returned by yabai that would have some "inf" values making it incorrect.

I'll look into a better fix that would prevent this title corruption.

**Comment by Jean-Tinland** [comment]
I simply removed this string replacement. I'll wait for the original bug to show up before fixing it with a more precise solution. Thank you for reporting this!

**Comment by jming422** [comment]
> I simply removed this string replacement. I'll wait for the original bug to show up before fixing it with a more precise solution. Thank you for reporting this!

You're welcome, and thank you!
