### ISSUE TITLE
Freshly installed simple-bar gets me a 'simple-bar-spaces.jsx: Something went wrong'

### ISSUE THREAD

**Issue by two-taps** [Jean-Tinland/simple-bar#218]
hi

I'm just starting to play around with simple-bar.

I basically installed yabai, then installed ubersicht, and then simple bar.

As soon as I started it, I get an error on simple-bar-spaces.jsx , I can't figure out why.
simple-bar-data.jsx works perfectly fine.

Screenshot for help:

<img width="1680" alt="Screen Shot 2021-09-11 at 6 03 24 PM" src="https://user-images.githubusercontent.com/30188512/132967338-dccb5226-267d-41f2-8cd8-06e265f07911.png">

**Comment by Jean-Tinland** [comment]
Hi!

If you do a:
```shell
which yabai
```

What is the ouput?

If you installed `yabai` in a custom path, you will need to add the custom path in `simple-bar` settings. You can open the settings by clicking first on `simple-bar` and then press the `cmd + ,` keys.

Let me know if this solves your issue!

**Comment by Jean-Tinland** [comment]
Feel free to re open this issue if necessary!

**Comment by iwa** [comment]
letting a comment just to explain how i fixed this, as i ran into a similar issue :

now homebrew will most likely install everything under `/opt`, so you need to grab the actual executable absolute path with
> which yabai

then copy the path, and paste it in simple-bar settings in `yahia path`
it should reload properly and work fine!
