### ISSUE TITLE
music string output 

### ISSUE THREAD

**Issue by Sylenss** [Jean-Tinland/simple-bar#222]
Hello, Jean its me again 

I seem to be having trouble with changing the string output for the music on the simple bar and its also not showing the full contents of song, is that an issue with the font im using or do I have to do something to expand the with in the debug console settings? Should I have mpc downloaded for the string to update, as well. 

![CleanShot 2021-09-14 at 21 04 37](https://user-images.githubusercontent.com/45975952/133354397-91c2fb11-4e24-471d-9071-3a278f41f01a.png)

![CleanShot 2021-09-14 at 21 17 44](https://user-images.githubusercontent.com/45975952/133355003-de901ed3-bf56-460e-8a5d-5ac7e634bd33.png)

**Comment by Jean-Tinland** [comment]
Hi!

This tab in settings only impact the MPD widget. String output is not customisable in Music/iTunes, Spotify & Browser Tracks widgets!

**Comment by Sylenss** [comment]
Oh wow, I wasn't aware of that, but is there a way that I can fix the overlapping of the string song, its suppose to say "one more light - linkin park " but its being overlapped

**Comment by Sylenss** [comment]
> Its not overlapping, its truncated because very long titles could break the entire bar. If you hover your mouse over it, it will start moving until the end.

Good day, I was also not aware of that, thank you for letting me know that! The hover mouse feature is not working for me and I also watch a streamer who also uses simple-bar, he was the person who introduce me to this! but in the screen shot he has a long title there that reveals his task for a programming stream and it seems to be working just fine
![CleanShot 2021-09-24 at 05 02 32@2x](https://user-images.githubusercontent.com/45975952/134649359-2ab8e6a8-77a0-4256-86dc-16cc50c1c3b6.png)

![CleanShot 2021-09-24 at 05 03 46@2x](https://user-images.githubusercontent.com/45975952/134649321-2cfb57c6-76cc-4ddd-9fd1-b6b48a125a20.png)

**Comment by kvndrsslr** [comment]
Have you updated your simple-bar repository to the HEAD?

**Comment by Sylenss** [comment]
> Have you updated your simple-bar repository to the HEAD?

Im honestly not sure, how do I check if I am?

**Comment by kvndrsslr** [comment]
you can run `git pull` from the command line in the simple-bar directory to make sure you are (given that you haven't done anything to the working directory)
