### ISSUE TITLE
Crypto and Zoom widgets displaying light text in light themes

### ISSUE THREAD

**Issue by beatslikeahelix** [Jean-Tinland/simple-bar#226]
![Screenshot 2021-09-23 at 18 00 52](https://user-images.githubusercontent.com/47506872/134551497-5ec8afed-087b-4325-92c7-5941af956668.png)

I assume this is a bug, but it could be unique to my setup. Has anyone else experienced this issue?

In the default theme, the text isn't readable at all. I'm currently using MacOS Light/Dark.

**Comment by Jean-Tinland** [comment]
This should be fixed now!

Thank your for reporting this :)
