### ISSUE TITLE
[Feature request] character limit and on-hover effect for custom widget and adjusting the position of process widget

### ISSUE THREAD

**Issue by albert-ying** [Jean-Tinland/simple-bar#228]
Hi, I noticed that my current process widget is usually overlapped with my widgets on the right side.

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/59846322/136300010-17f8d673-1acf-4188-8fce-9d82d729bba3.png">

I'm wondering if it is possible to let the custom widgets to have a similar on-hover effect as the music widget (i.e., animation to show the rest of the string that exceeds the character limit).

It would be very useful for most of user widgets like calendar or todo list ...etc

Also, it would be nice to be able to adjust the position of the process widget to avoid the overlap. Currently, it is right at the middle by default, however, there is usually more space on the left side.

Thank you!

**Comment by Jean-Tinland** [comment]
Hi, this would be indeed usefull, I'll implement it soon!

**Comment by Jean-Tinland** [comment]
Similar as #233
