### ISSUE TITLE
Zoom widget is greyed out

### ISSUE THREAD

**Issue by rpbaptist** [Jean-Tinland/simple-bar#232]
First of all, thank you for this awesome widget. It's beautiful and has many options out of the box.

I'm trying to get the Zoom widget to work, but no luck. It's greyed out and no matter what, I can't get it to recognize my Zoom app. Do you have any pointers?

![image](https://user-images.githubusercontent.com/7916262/137167670-6af4fe7c-9b6c-495c-aaab-26ca26f78056.png)

**Comment by Jean-Tinland** [comment]
I'm closing this for now, if anyone is still experience this feel free to re open it or create a new issue!
