### ISSUE TITLE
How to change Volume refresh rate?

### ISSUE THREAD

**Issue by AurevoirXavier** [Jean-Tinland/simple-bar#242]
It didn't immediately change when I use keyboard shortcut to change the volume

**Comment by Jean-Tinland** [comment]
Indeed, the volume widget is refreshed every 20 seconds in order to prevent battery draining.

If I could I would set all refresh frequencies of all widgets to 1 second but that would make the battery melt.

**Comment by AurevoirXavier** [comment]
> Indeed, the volume widget is refreshed every 20 seconds in order to prevent battery draining.
> 
> If I could I would set all refresh frequencies of all widgets to 1 second but that would make the battery melt.

I think it's okay. Istat refresh rate is 1s. And they got many users.

And 20s is okay too, but if there is an option that I can change the fresh rate that would be better.

**Comment by Jean-Tinland** [comment]
I implemented a user override in settings for all data widgets. You should now be able to set the refresh rate you want. :)

**Comment by AurevoirXavier** [comment]
But seems the crypto doesn't fetch the latest price every second. I set refresh rate to 1000 ms.

**Comment by AurevoirXavier** [comment]
Does it require an API key?

**Comment by Jean-Tinland** [comment]
Are the markets opened?

**Comment by AurevoirXavier** [comment]
> Are the markets opened?

Yes. Maybe the price doesn't change that fast.

Looks good now.

Thanks. Great job.
