### ISSUE TITLE
Can not show Chinese keyboard

### ISSUE THREAD

**Issue by AurevoirXavier** [Jean-Tinland/simple-bar#243]
When I switch keyboard from US to CN, the icon gone

When I switch back to US, the icon shown up

**Comment by Jean-Tinland** [comment]
This particular widget need some work in order to be fully functionnal and really usefull, I'll look into it soon. :)

**Comment by Jean-Tinland** [comment]
It seems that I can't detect some keyboard layouts as the output of this command:

```shell
defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources
```

Usually returns this (with a french input source):
```text
(
        {
        "Bundle ID" = "com.apple.PressAndHold";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.EmojiFunctionRowItem";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        InputSourceKind = "Keyboard Layout";
        "KeyboardLayout ID" = 1;
        "KeyboardLayout Name" = French;
    }
)
```

I'm using this line : `"KeyboardLayout Name" = French;` which is not existing with tradional chinese:

```text
(
        {
        "Bundle ID" = "com.apple.PressAndHold";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.EmojiFunctionRowItem";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.TCIM";
        "Input Mode" = "com.apple.inputmethod.TCIM.Cangjie";
        InputSourceKind = "Input Mode";
    }
)
```

I'll let you know if I find a proper solution.

**Comment by HeySora** [comment]
If it can help, here is how that file looks on my end with Japanese keyboards

Maybe you can fetch in some way a readable string from the Bundle ID?

<img width="633" alt="image" src="https://user-images.githubusercontent.com/17962248/141094946-0b4cfdb2-fcc9-4867-ac72-ac5a4c6baba9.png">

**Comment by Jean-Tinland** [comment]
Indeed, thank you for your input, I think I handled it well. I pushed it in master. Let me know if you have any problem. :)

**Comment by AurevoirXavier** [comment]
> Indeed, thank you for your input, I think I handled it well. I pushed it in master. Let me know if you have any problem. :)

Great job. It works.

But why it shows 

![image](https://user-images.githubusercontent.com/16152305/141133983-cad3c62f-aa26-44fb-bd6c-d85142c68262.png)

I'm using Chinese PinYin, what's the meaning of ITABC?

**Comment by Jean-Tinland** [comment]
It seems that this is the name Apple gave to this input source (Chinese PinYin simplified):

```text
(
        {
        "Bundle ID" = "com.apple.PressAndHold";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.EmojiFunctionRowItem";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.SCIM";
        "Input Mode" = "com.apple.inputmethod.SCIM.ITABC";
        InputSourceKind = "Input Mode";
    }
)
```

I'm always getting the last part of this line: `"Input Mode" = "com.apple.inputmethod.SCIM.ITABC";`

In Chinese PinYin traditional I have this result:

```text
(
        {
        "Bundle ID" = "com.apple.PressAndHold";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.EmojiFunctionRowItem";
        InputSourceKind = "Non Keyboard Input Method";
    },
        {
        "Bundle ID" = "com.apple.inputmethod.TCIM";
        "Input Mode" = "com.apple.inputmethod.TCIM.Pinyin";
        InputSourceKind = "Input Mode";
    }
)
```

Here "Pinyin" is displayed as this is the last part of this line: `"Input Mode" = "com.apple.inputmethod.TCIM.Pinyin";`.

I don't think I can do better with the current implementation of this widget. I'll keep in mind the issue if I'm working on this again.

**Comment by nilsi** [comment]
It would be nice if we could get the language codes instead. For example SE for Swedish. For me it shows Swedish - Pro which is too long for the widget. Or if we add flags that we can swop between depending on the ID.
