### ISSUE TITLE
When yabai is not launched, localnode takes a lot of CPU

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#246]
It looks like simple-bar is retrying yabai commands a bit too often, when yabai is not running.

Would it be better to handle the case when yabai is not running? So, instead of showing `'Something went wrong'`, show `'yabai is not running!'` then wait 10-15 seconds until the next check of whether it's running?

**Comment by HeySora** [comment]
Thank you a lot, you're a blessing 🙏

**Comment by HeySora** [comment]
https://user-images.githubusercontent.com/17962248/141655430-75fb5047-2ea7-4719-8c20-71328783e759.mov

I don't think it works well @Jean-Tinland  😅

**Comment by Jean-Tinland** [comment]
That's weird, I tested It by manually stopping yabai and it was working fine. I'm looking into it soon. :)

**Comment by HeySora** [comment]
I tried manually stopping it 10 times, and 3 reproduced that behaviour. So what you did was definitely better at least!

The only error present in Übersicht's logs is "Request timed out", being spammed quite a lot.  
I'm guessing it's a race condition issue where simple-bar is making a yabai query at the same time it closes (which happens OFTEN because on Monterey, yabai sometimes crashes when doing queries), and either some part of the code is retrying the yabai query, or `pgrep yabai` is getting fooled by the queries simple-bar is doing.

I don't know much about `pgrep` but I think it is possible to get the arguments given to a particular running program, so if the running yabai instance's arguments contains `--query`, then it should not be considered as running.

**Comment by Jean-Tinland** [comment]
Let me know if this problem is still occurring with my latest commits. :)

**Comment by HeySora** [comment]
I don't think it's still happening, thank you! :)
