### ISSUE TITLE
[suggestion] light & dark theme.js

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#25]
Hi Jean,

I have another suggestion, I would like to see the light and dark theme as two separate files, something like dark_theme.js and light_theme.js

Currently, the light theme is "hardcoded" in the man style.js making it harder to maintain with the constant updates (even if the updates are great 👍)

What do you think?

**Comment by Jean-Tinland** [comment]
Hi,

Yes I could indeed make some changes at this level.

How would you see that?

Currently, theme switching is operated by system preferences. Base theme is the dark one and with the `preferred-color-scheme` CSS media query,  only colors are overriden when user has selected light theme.

I could declare both dark & light full styles (layout and colors) in their own separate file and import only the one needed. Or I could import both and let the CSS media query operate.

Is it more or less what you were suggesting? 

I don't know if I'm answering correctly to your suggestion :)

**Comment by MikoMagni** [comment]
I was thinking along the line of declaring both dark and light styles in separate files. 

`import only the one needed. Or I could import both and let the CSS media query operate.`

Either options would work fine, but really no rush or urgency as i mostly use pywal :)

**Comment by Jean-Tinland** [comment]
I see, I will soon work on something that will be more easily maintainable.

**Comment by MikoMagni** [comment]
@Jean-Tinland Seriously no rush but thank you. 

I was thinking over the weekend that it would be great to make the data modules more modular so that they can be toggled on and off. 
But not sure there is an easy way of doing that without having to change a lot of the code.  

I have a few extras bits and pieces that I was testing with CPU/RAM and network speed. The problem is that it is right on a 30" screen but not so good on my MBP.  That is what made me think about separating the data modules in several widgets.

Just ideas, simple bar is excellent as is :)

**Comment by Jean-Tinland** [comment]
I'm working on a Settings module:
![image](https://user-images.githubusercontent.com/43068795/95060259-530ec680-06fa-11eb-9410-bcd2b3272253.png)

With this module you could enable/disable each individual `data` widget. Each additional widget could be also added here.

I think it is better to keep all data widgets in a parent Übersicht widget principaly because I don't know how to handle layout with individual `fixed` positioned widgets.

With this Settings module I'm also working on a better dark/light theme implementation.

What are your thought about that?

**Comment by MikoMagni** [comment]
That looks great, and most certainly make a lot of sense with the widgets positioning.

**Comment by MikoMagni** [comment]
Thanks for last update. Closing this one
