### ISSUE TITLE
JavaScript Error in spaces.jsx

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#251]
This happens consistently, with SIP disabled, and the official yabai version.  
It sometimes happens with SIP enabled and the donaldguy fork, but quickly disappears in less than a second.

![image](https://user-images.githubusercontent.com/17962248/142203383-8eddf7f0-e36c-465b-83eb-d7d4c7638f29.png)

I did `console.log(spaces)` and `console.log(spaces.find(({ visible, display }) => visible && display === displayIndex))` just above the erroring line, the two results are :

![image](https://user-images.githubusercontent.com/17962248/142204347-8ddc7a03-fb62-40c0-b620-05b894b6e783.png)

So the issue is that spaces.find(...) returns `undefined`

**Comment by HeySora** [comment]
Replacing `{visible, display}` with `{ 'is-visible': visible, display: display }` now makes this error appear only on the unfocused monitor. The focused monitor will have all spaces but without any application inside.

**Comment by Jean-Tinland** [comment]
It's the same issue as #253, if you pull the master you shouldn't have this error anymore. :)
