### ISSUE TITLE
Break in yabai 4.0

### ISSUE THREAD

**Issue by albert-ying** [Jean-Tinland/simple-bar#253]
![image](https://user-images.githubusercontent.com/59846322/142517032-34b1d7d1-c52c-4624-9621-65ad663cba6a.png)

Any clue what is happening here?

see https://github.com/koekeishiya/yabai/blob/the-future/CHANGELOG.md

And https://github.com/koekeishiya/yabai/issues/923

**Comment by Tchoupinax** [comment]
Hello :)

I exactly met the same error.

**Comment by koekeishiya** [comment]
The output from the query system has changed. See https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#query

**Comment by Headscracher** [comment]
Got the same problem on Monterey. I made some quick changes to workaround this issue.  
Headscracher/simple-bar@bd1454fa13f332244078de75439acbda0a4d8c9e
It's not perfect, but at least no error messages are thrown around.
The undefined if statement needed to be added since yabai sometimes would give me any visible spaces.

**Comment by albert-ying** [comment]
Hi @Headscracher , thank you for your work. I tried your fork and the error indeed stoped and it shows me the correct number of spaces.

But it still doesn't highlight the current space. And the current process widget is disappeared. I also noticed that I could not toggle the preference window when pressing `cmd + ,`.

Just want to confirm that if you also have these problems (or it is some bug due to my setting)? I'm on M1 MacOS 12.0.1 .

**Comment by Headscracher** [comment]
Yeah thats right. Was just a quick patch to get rid of the errors. I didnt use this repo before and encountered this problem. So I dont know how a default installation should look and work like. If I get around the other problems I'll let you know.

**Comment by lamtuanvu** [comment]
I have updated following the output from yabai v4.0.0. It's still not updated completely (e.g: for multiple display detection) but essential features worked. Please checkout [here](https://github.com/lamtuanvu/simple-bar/commit/8b17222fe33e89cb8903f0bff50eb7af8eacc148)

**Comment by Jean-Tinland** [comment]
I haven't updated yabai yet but I'll look into it today.

**Comment by Tchoupinax** [comment]
> I have updated following the output from yabai v4.0.0. It's still not updated completely (e.g: for multiple display detection) but essential features worked. Please checkout this [fork](https://github.com/lamtuanvu/simple-bar/commit/8b17222fe33e89cb8903f0bff50eb7af8eacc148)

I confirm that the fork works.

**Comment by christo-ph** [comment]
> I have updated following the output from yabai v4.0.0. It's still not updated completely (e.g: for multiple display detection) but essential features worked. Please checkout this [fork](https://github.com/lamtuanvu/simple-bar/commit/8b17222fe33e89cb8903f0bff50eb7af8eacc148)

With this fork the initial error appears again. With @Headscracher fork at least the spaces are shown properly.

**Comment by Jean-Tinland** [comment]
I'm working on making simple-bar supports both yabai v3 and yabai v4. It should be ready soon. :)

**Comment by Jean-Tinland** [comment]
Master is now supporting both yabai v3 and yabai v4. Please let me know if you see anything unusual. I have everything working fine on **Intel Monterey**.

**Comment by Jean-Tinland** [comment]
Okay, I'll try to reproduce tomorrow, I don't have a 2nd display at home. :)

**Comment by christo-ph** [comment]
@Jean-Tinland now It works on the main/active display as @Headscracher mentioned and on the second display there is still the error with `currentSpace.index`

Thank you so far!

**Comment by Jean-Tinland** [comment]
Should be better now!

**Comment by Headscracher** [comment]
Now it's working. Thanks a lot.

**Comment by christo-ph** [comment]
Thank you! Perfect.
