### ISSUE TITLE
Error in spaces.jsx - Error running command

### ISSUE THREAD

**Issue by kavinvalli** [Jean-Tinland/simple-bar#254]
Randomly sometimes, I get the following error
![Screenshot 2021-11-19 at 9 01 48 AM](https://user-images.githubusercontent.com/41034356/142560337-77320f80-ec7b-4847-93ce-eefa2ed4f9f3.png)

![Screenshot 2021-11-19 at 9 03 03 AM](https://user-images.githubusercontent.com/41034356/142560438-c973c441-9f1c-4b43-ad69-f2e5e8c17952.png)
and the bar starts showing:`simple-bar-spaces.jsx: Something went wrong`.
After I refresh the bar a couple of times, it's fine

**Comment by albert-ying** [comment]
I have exact same problem (in both intel big sur and M1 Montery). This is quite annoying, as it happens quite frequently. Just to add something:

1. the yabai terminal also gives these errors
```
45:86: 45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: 45:86:45:86:  45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
45:86: execution error: Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx". (-1728)
```

Another thing is, not sure it is problem of Übersicht or simple bar (as I only run simple bar in Übersicht), the Übersicht uses so many resources. It has larger energy impact then firefox + vs code. And sometime it make my laptop stuck, especially when those errors happens (this is insane, as I'm using an M1max 64g Ram MacBook!).

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/59846322/142987922-e06ccdc6-24e2-4a9c-91d6-d08cbd9d6a7e.png">

<img width="957" alt="image" src="https://user-images.githubusercontent.com/59846322/142988018-906e3237-2084-468f-ad2c-88fc8209404a.png">

**Comment by Jean-Tinland** [comment]
I just increased the delay between each simple-bar's refresh. This should reduce the amount of ressources needed.

Are you still experiencing this issue with the latest version?

**Comment by albert-ying** [comment]
@Jean-Tinland Thank you for the quick response! I just updated to the latest version. The Übersicht still at top of the list if sorted by energy impact. But the CPU usage decreased from always ~ 100% to ~ 75-80% (the process "localnode")

The error mentioned before still happens a lot. (happened 4 times while I'm typing this, and frozed my editor). It calms down a little bit after refreshing the widgets through Übersicht, but it come back again after a while. Do you know what may cause this?

**Comment by Jean-Tinland** [comment]
Unfortunately I can't reproduce this issue for now. 

What is your OS version? Also, are you running simple-bar on a M1 chip or an Intel one?

**Comment by albert-ying** [comment]
I'm on M1 chip, MacOS 12.0.1.

**Comment by kavinvalli** [comment]
Same. M1 MacOS 12.0.1

**Comment by Jean-Tinland** [comment]
Okay, have you upgraded yabai to v4?

**Comment by kavinvalli** [comment]
@Jean-Tinland I upgraded yabai to v4. Still getting the error

**Comment by Jean-Tinland** [comment]
I can't reproduce this issue as I'm running simple-bar on an Intel Mac book pro. If anyone has an idea it would be really helpful!

**Comment by kavinvalli** [comment]
@Jean-Tinland I noticed a pattern that the issue starts when I run [Amazon Prime Video](primevideo.com). I'm not sure if it is related but it might have some significance

**Comment by licht1stein** [comment]
I have the same error from the start, it never showed the spaces.

Apple M1, Mac OS 12.2

**Comment by mhsars** [comment]
If you are using a device with an Apple Silicon processor and you have installed yabai through homebrew, keep in mind that homebrew's file path is different for Apple Silicon devices.

Click on simple-bar (a bar pops up even if it shows an error) and press CMD + , to open the settings screen of simple-bar. Make sure the yabai path is "/opt/homebrew/bin/yabai" here.

If you are using macOS Big Sur or Monterey, the same situation (homebrew path) can be found in the file "/private/etc/sudoers.d/yabai" written for the yabai script to start automatically at startup.

<user> ALL = (root) NOPASSWD: /usr/local/bin/yabai --load-sa

"/opt/homebrew/bin/yabai" should be instead of "/usr/local/bin/yabai"

Also to find out on which path yabai is located, you can type "which yabai" in the terminal. 

I hope it will be useful for someone.

**Comment by miiraheart** [comment]
I am facing the same problem but the recommendation do not work, on mac Sequoia 15.2 M1
