### ISSUE TITLE
Battery widget broken on M1 Max Monterey

### ISSUE THREAD

**Issue by issmirnov** [Jean-Tinland/simple-bar#258]
Hey @Jean-Tinland , thanks for the hard work getting this to work with yabai v4.0. Everything works great! 

I did notice the battery widget seems busted. It keeps spinning and doesn't show any data:

![Screen Shot 2021-11-24 at 13 07 36](https://user-images.githubusercontent.com/5771615/143306522-a50eb646-d22a-4522-b30e-7b8a2b6d88b4.png)

Logs show:

![Screen Shot 2021-11-24 at 13 07 53](https://user-images.githubusercontent.com/5771615/143306565-cac45fa1-60c8-45ff-a592-0687853825ff.png)
 

Seems to be coming from `battery.jsx` line 43.

I ran the `pmset` commands manually, and they worked fine:

```
$ pmset -g batt | egrep '([0-9]+%).*' -o --colour=auto | cut -f1 -d'%'"
100
```

I looked at `Utils.getSystem` and it's present in `lib/utils.js` on d5c5c3c . 

Not sure what's going on here, as JSX isn't my strong point.

Any thoughts? This is running d5c5c3c, with no changes by me.

**Comment by Jean-Tinland** [comment]
Thanks!

This is weird indeed. Have you completely restarted Übersicht?

You could try to remove your simple-bar directory and re clone it (settings are stored in Übersicht so you won't loose anything).

Let me know if this is solving your issue.

**Comment by issmirnov** [comment]
Hey,

I restarted Übersicht and it solved the problem. Should have tried that
first :)

Thanks!
--
Ivan Smirnov
https://ivans.io/ | https://blog.ivansmirnov.name/
https://www.linkedin.com/in/ismirnov |
*https://ivansmirnov.name/ <https://ivansmirnov.name/>*
*https://github.com/issmirnov <https://ivansmirnov.name/>*

**Comment by Jean-Tinland** [comment]
After massive changes Übersicht has sometimes some trouble realoding everithing perfectly. It is safer to restart Übesicht after each simple-bar's update. :)
