### ISSUE TITLE
Something went wrong with simple-bar-data

### ISSUE THREAD

**Issue by sambilbow** [Jean-Tinland/simple-bar#26]
MacOS Catalina 10.15.6
Ubersicht downlaoded app.zip
Yabai installed and running through brew services
SIP disabled

Getting this error "Something went wrong . . ." showing on the right side of the status bar and no date/time/wifi just the text error. Spaces are working well with Yabai. Have recloned to no avail.

Thanks

**Comment by sambilbow** [comment]
Hopefully these help.

![Screenshot 2020-09-29 at 14 24 01](https://user-images.githubusercontent.com/31018239/94564171-90d5a000-025f-11eb-8704-ed1a51f6473a.png)
![Screenshot 2020-09-29 at 14 21 48](https://user-images.githubusercontent.com/31018239/94564176-9337fa00-025f-11eb-84b5-3a682c0f262e.png)

**Comment by Jean-Tinland** [comment]
Hi !
If you are having this error, It may be because of one of the command run in the `get_data.sh` script on widget init.

```sh
BATTERY_PERCENTAGE=$(pmset -g batt | egrep '([0-9]+\%).*' -o --colour=auto | cut -f1 -d'%')
BATTERY_STATUS=$(pmset -g batt | grep "'.*'" | sed "s/'//g" | cut -c 18-19)

BATTERY_CHARGING=""
if [ "$BATTERY_STATUS" == "Ba" ]; then
  BATTERY_CHARGING="false"
elif [ "$BATTERY_STATUS" == "AC" ]; then
  BATTERY_CHARGING="true"
fi

WIFI_STATUS=$(ifconfig en0 | grep status | cut -c 10-)
WIFI_SSID=$(networksetup -getairportnetwork en0 | cut -c 24-)

VOLUME=$(osascript -e 'set ovol to output volume of (get volume settings)')
MUTED=$(osascript -e 'set ovol to output muted of (get volume settings)')

SPOTIFY_IS_RUNNING=$(osascript -e 'tell application "System Events" to (name of processes) contains "Spotify"')
```

You could try to run each of these commands individually from you terminal:

```sh
# battery level
$ pmset -g batt | egrep '([0-9]+\%).*' -o --colour=auto | cut -f1 -d'%'

# battery status
$ pmset -g batt | grep "'.*'" | sed "s/'//g" | cut -c 18-19

# wifi status
$ ifconfig en0 | grep status | cut -c 10-

# wifi network name
$ networksetup -getairportnetwork en0 | cut -c 24-

# volume level
$ osascript -e 'set ovol to output volume of (get volume settings)'

# volume is muted?
$ osascript -e 'set ovol to output muted of (get volume settings)'

# check if Spotify is runing
$ osascript -e 'tell application "System Events" to (name of processes) contains "Spotify"'

# Spotify state
$ osascript -e 'tell application "Spotify" to player state as string'
```

If you encounter an error with one of these it would explain why the data widget is broken.

Let me know if you encounter a problem while running these commands.

Also, the first time simple-bar is launched, you should be prompted by Ubersicht to allow it to access some data from other apps like Spotify or some system data. You need to agree to these messages.

**Comment by sambilbow** [comment]
![Screenshot 2020-09-30 at 14 35 26](https://user-images.githubusercontent.com/31018239/94692202-2f2e3800-032a-11eb-995f-9170d1232970.png)

Getting missing value on audio settings because I'm using an external interface that stops the OS from changing volume level.

Switched to laptop speakers and recloned. Still getting the error. How can I check that simple-bar has all of the permissions it needs? I'm pretty sure I said yes to everything.

**Comment by Jean-Tinland** [comment]
Okay, thank for this screenshot. I think the problem is not located here.

I added some logs in `data` widget, could you please paste them here or take a screen shot?

I've also pushed a fix that hide `Sound` widget if returned value is "missing value".

**Comment by sambilbow** [comment]
Thanks for the commit :) 

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (run, line 0)

[Log] undefined (simple-bar-data-jsx, line 1079)
Error: ./simple-bar/lib/scripts/browser_audio.applescript:615:618: script error: Expected class name but found property. (-2741) { "battery": { "percentage": "100", "charging": "true" }, "wifi": { "status": "active", "ssid": "kirei no wasabi" }, "sound": { "volume": "missing value", "muted": "missing value" }, "spotify": { "spotifyIsRunning": "true", "playerState": "playing", "trackName": "First Morning Out", "artistName": "Joanna John" }, "browserTrack": } — client.js:1:903438

**Comment by Jean-Tinland** [comment]
I've improved the `get_data.sh` script in order to catch the error happening in the applescript script.
Let me know if this is fixing your problem.

Doing so, people encountering error may not see the current browser track widget but the other widgets are still displayed.

**Comment by sambilbow** [comment]
Thank you so much for your time. Issue fixed.
