### ISSUE TITLE
Space focus is not working correctly after certain time

### ISSUE THREAD

**Issue by Frankcs96** [Jean-Tinland/simple-bar#261]
Hi!, I've been using simple bar for one week and I've always had this problem.
Everything works fine but after 5-10 minutes the highlighted space is not changing anymore. as you can see in the picture I'm in zsh space but the highlighted space is stuck in browser.
![Screenshot 2021-12-23 at 07 45 04](https://user-images.githubusercontent.com/52538691/147199854-554fb531-589a-4444-b254-729473dad4c8.png)
My solution is just to restart the widget and everything works fine again, but again after 5-10minutes it's the same, also if I click the "+"sign and I add a new space works like a reset and it works again.
I'm using a m1 macbook pro monterey 12.0.1

**Comment by steven-lang** [comment]
I have the same behaviour - how did you fix this?
