### ISSUE TITLE
2021 m1 macbooks with notch support

### ISSUE THREAD

**Issue by yorhodes** [Jean-Tinland/simple-bar#263]
Any ideas for how to support notched displays?

The process widget is unusable because it gets totally obscured by the notch on my new m1 macbook

Having the process and other data widgets anchored to the center notch and expanding out leftward and rightward could be a clean look

**Comment by Jean-Tinland** [comment]
Indeed! For now the only solution preventing this issue is to set simple-bar position to bottom screen. I'll look into a proper way for handling this but I like what you are suggesting. :)

**Comment by den19980107** [comment]
@yorhodes can you show the current simple-bar on new macbook with notch look like?

i am very curious 😂

**Comment by stackpivot** [comment]
is there any progress on this topic? Im going crazy without the bar.

**Comment by yzhuang** [comment]
> @yorhodes can you show the current simple-bar on new macbook with notch look like?
> 
> i am very curious 😂
![IMG_20220313_223834](https://user-images.githubusercontent.com/423730/158112469-2dc553c4-c698-4be7-af15-eb7f032300bf.jpg)

**Comment by Jean-Tinland** [comment]
I indeed need to get this done, I'll keep you updated :)

**Comment by firexcy** [comment]
Second this. Or is there a quick patch we can manually apply so as to make the process section align immediately after the space section? Thanks.

**Comment by restfuladi** [comment]
> Second this. Or is there a quick patch we can manually apply so as to make the process section align immediately after the space section? Thanks.

Agreed, a process section aligned left would be fine for me. The right side is full of crypto tickers anyway.

**Comment by Jean-Tinland** [comment]
I added this option in settings:
<img width="495" alt="Screenshot 2022-05-16 at 16 05 35" src="https://user-images.githubusercontent.com/43068795/168611232-de7b8850-3c83-4824-bf84-39690ba9eb69.png">

Let me know if this is better now. :)

**Comment by restfuladi** [comment]
> I added this option in settings: <img alt="Screenshot 2022-05-16 at 16 05 35" width="495" src="https://user-images.githubusercontent.com/43068795/168611232-de7b8850-3c83-4824-bf84-39690ba9eb69.png">
> 
> Let me know if this is better now. :)
> 
> Edit: You'll need to restart Übersicht as I merged both widgets into one (data + spaces = index).

Works great, thanks!! 

One minor issue, looks like the rectangles are taller now and the top pixel or two is getting cut off.

**Comment by Jean-Tinland** [comment]
I'm closing this issue as the main topic has been resolved, feel free to open a new one if anything else is needed.
