### ISSUE TITLE
Separate Icons not showing for full-screen apps

### ISSUE THREAD

**Issue by Programmer1325** [Jean-Tinland/simple-bar#267]
I am using macOS Monterey with Yabai v4. The problem I have is that full-screen apps are not showing separate icons in the spaces bar.

![Screenshot 2022-01-20 at 8 35 19 AM](https://user-images.githubusercontent.com/87233999/150265105-891ee1f4-1083-4e1f-8f7c-8b7e6dbfb394.png)
On the spaces bar, Space 4 should be empty, but spaces 5 and 6 should be Chrome and Spotify respectively. I don't what is causing this since I have searched the whole settings. Other than that, simple bar is working great. Thanks

**Comment by Jean-Tinland** [comment]
Hi! I think this is related to #268 

I'll look into it soon :)

**Comment by Jean-Tinland** [comment]
This should be fixed on the latest yabai commit. :)

**Comment by Programmer1325** [comment]
Thank you for the quick responses :)
