### ISSUE TITLE
Icons all appear in same workspace on yabai v4

### ISSUE THREAD

**Issue by abhatthal** [Jean-Tinland/simple-bar#268]
I've discussed this with koekeishiya here: https://github.com/koekeishiya/yabai/issues/1131

Whenever I go to a workspace, the icons for apps in that workspace will be added along with all others previously seen.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/41220185/150401087-e5b58b68-93b1-4b86-a6b3-5453edbabf08.png">

This issue appears at HEAD, but not at [297156c](https://github.com/koekeishiya/yabai/commit/297156c02854f21a811f5593504226a040a60414). I know that v4 is still unreleased so a new change must have been made to the query output that the latest release of simple-bar hasn't addressed yet.

My temporary solution is rolling back to that older yabai commit where simple-bar works, hopefully it'll be fixed soon.

**Comment by Jean-Tinland** [comment]
Hi, thank you for reporting this! It seems that I've missed something while adding yabai v4 support, I'll look into it soon :)

**Comment by Jean-Tinland** [comment]
This should be fixed on the latest yabai commit. :)
