### ISSUE TITLE
Get data script fails when Spotify is open but not playing a track

### ISSUE THREAD

**Issue by jamieweavis** [Jean-Tinland/simple-bar#27]
There is an edge case where the `get_data.sh` script fails when Spotify is open but there isn't a song currently playing/selected which means that all of the data widgets fail to display

I think that Spotify can get into this state after a system reboot

```sh
55:61: execution error: Can’t make name of «class pTrk» of application "Spotify" into type string. (-1700)
57:63: execution error: Can’t make «class pArt» of «class pTrk» of application "Spotify" into type string. (-1700)
{ "battery": { "percentage": "100", "charging": "true", "remaining": "0:00" }, "wifi": { "status": "active", "ssid": "Cooper" }, "sound": { "volume": "31", "muted": "false" }, "spotify": { "spotifyIsRunning": "true", "playerState": "stopped", "trackName": "", "artistName": "" } }
```

We should probably hide the Spotify widget if the `trackName` and `artistName` are empty strings?

**Comment by Jean-Tinland** [comment]
Indeed, I encounter the very same problem with the BrowserTrack widget.

I've added a more precise test in Spotify widget in order to test `trackName` & `artistName`:
```javascript
if (spotifyIsRunning === 'false' || trackName === '' || artistName === '') return null
```

I also updated the `get_data` file:
```sh
SPOTIFY_IS_RUNNING=$(osascript -e 'tell application "System Events" to (name of processes) contains "Spotify"' 2>&1)
```

A return error code was producing an error in the global `data.jsx` widget so nothing was rendered.

Let me know if this is fixing the issue.

**Comment by jamieweavis** [comment]
Thanks for the quick fix!

I haven't been able to confirm that it's fixed yet because I couldn't get Spotify to be in that state again...

This can probably be closed now, let's re-open if it pops up again 👍

**Comment by Galactic-Dev** [comment]
I still get this issue
