### ISSUE TITLE
simple-bar-spaces.jsx: Something went wrong...

### ISSUE THREAD

**Issue by licht1stein** [Jean-Tinland/simple-bar#270]
Macbook Air M1
Mac OS 12.2

Yabai works as expected. simple-bar-data.jsx also works.

How do I fix this?

**Comment by licht1stein** [comment]
@Jean-Tinland I'm ready to work on it a submit a pr, just need some directions on where to start :)

**Comment by licht1stein** [comment]
Ok, in my case it was fixed by changing default path to yabai from `/usr/local/bin/yabai` to whatever `which yabai` showed.

**Comment by B1T3X** [comment]
I would like to chime in and say I'm facing the same issue on a M1 mac, and the proposed solution didn't work for me. I know it isn't fully supported but I'd be super happy to contribute as a tester of this awesome bar. :)

**Comment by prgres** [comment]
@B1T3X try to change it in `settings.Js` file. I had changed it in `index.Jsx` and had the same problem
