### ISSUE TITLE
Cannot open settings + spaces widget is not interactive.

### ISSUE THREAD

**Issue by licht1stein** [Jean-Tinland/simple-bar#271]
I have cloned simple-bar, and need to set the custom yabai directory. But clicking anywhere on "Something went wrong" or any of the other widgets, and then pressing Cmd+, doesn't open settings.

What can I do? Is there a way to edit settings manually?

Mac OS: 12.2
MacBook Air M1

UPDATE:

The symptoms I have after I manually edited the yabai path in the source files.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/35418634/152217806-a705aeb7-4ebb-48da-b16b-10a571a9c167.png">

1. None of the spaces widget elements are interactive. I cannot use the mouse to switch spaces.
2. There is no way to open settings, since none of the spaces bar elements are interactive. Clicking on the bar and then Cmd+, just opens Finder settings.

**Comment by Jean-Tinland** [comment]
Hi, have you checked if in your Übersicht settings you have selected "Enable interactions"?

**Comment by licht1stein** [comment]
Even half-working as now simple-bar is an integral part of my work :)

**Comment by Jean-Tinland** [comment]
What version of yabai are you using?

If you install yabai v4 everything should work as excepted. Installation process here: [https://github.com/koekeishiya/yabai/issues/1054](https://github.com/koekeishiya/yabai/issues/1054)

**Comment by licht1stein** [comment]
Yes it should. I do have yabai v4 though.

**Comment by licht1stein** [comment]
Here's the video of the debug log going crazy:

https://youtu.be/ZBEK5EUVqYI

**Comment by Jean-Tinland** [comment]
Your settings may be corrupted since you manually edited it, you could try to cleanup the Übersicht storage by removing the simple-bar's storage row and try to restart it.

**Comment by licht1stein** [comment]
What exactly do you mean by "simple-bar's storage row"?

**Comment by licht1stein** [comment]
All I edited was the path to yabai executable — otherwise it just wouldn't work. I don't think this can affect interactivity or access to settings, can it?

**Comment by Jean-Tinland** [comment]
My message was indeed a bit vague :)

I mean you can remove this row in Übersicht console:
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/43068795/153627003-59a736d9-9023-4ad5-a58b-f1fe2b9ca455.png">

Then quit & relaunch Übersicht. If you need to change the yabai path, you can do if after even if the bar is showing and error on the left. You simply need to cick on the middle of the bar then press `cmd + ;`.

The settings can be corrupted if the json containing them is broken (a simple missing quote for example).

**Comment by licht1stein** [comment]
It seems the settings never get initiated

**Comment by licht1stein** [comment]
Can you maybe add an alternative way to open settings? Like right clicking the battery icon, for example

**Comment by RollingRo11** [comment]
I'm having the exact same problem with the exact same errors in the error log, and steps to get there. I also had to change the files to change the path to yabai because I can't open settings

I also CAN interact with the widgets on the right (battery, volume, sound, wifi, date, time)

But my local storage in the ubsersicht console also doesn't have anything to clear.

**Comment by Jean-Tinland** [comment]
I'm sorry I haven't had time to look into this issue yet, I'll keep you updated as soon a I can :)

**Comment by bunself** [comment]
Any update on this? I'm experiencing the same issues.

**Comment by Sylenss** [comment]
Im currently experiencing the same issue, I have yabai4.0 installed and also checked to see if SIP was disable which it is on my system
![CleanShot 2022-03-19 at 08 12 31](https://user-images.githubusercontent.com/45975952/159120670-39428c28-8de6-42f3-9266-731093410964.gif)

**Comment by Jean-Tinland** [comment]
@licht1stein can you look in your `/Users/mb/.profile` file? It seems that there is a problem with `pyenv`.

I also saw that you were having problems with the `slidingAnimationPace` in settings so I've made some changes where it is used in order to prevent the bar to break if it is undefined. Let me know if this is better.

I'm sorry, this is hard to find the origin of theses problems without a M1 mac to test/reproduce them.

**Comment by licht1stein** [comment]
Here's the content of my .profile

```bash
$ cat .profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export PATH="$HOME/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"
export GPG_TTY=$(tty)
```

**Comment by licht1stein** [comment]
I've stashed all changes I made and pulled the changes. Still getting "Something went wrong..."

**Comment by Jean-Tinland** [comment]
I don't think accessing to the settings interface will change anything, these a just the same thing as the object in `settings.js`. There is another problem that prevent simple-bar to initialize fully.

Can you try to check "Load bash env" in the Übersicht settings?

**Comment by licht1stein** [comment]
Yes, didn't change anything.

**Comment by Spaxly** [comment]
I am having this issue as well, nothing shows in local storage either. Anyway to fix?

**Comment by alexeydemidovkz** [comment]
Not sure if this is right thread to write. I have Simple Bar and everything works fine (changing spaces and processes on click) , I changed the path to yabai and turned off some widgets by editing settings.js. But I can't open settings with cmd+ nothing happens.

**Comment by Spaxly** [comment]
This issue has been fixed by changing the path.

**Comment by licht1stein** [comment]
I was never able to even open settings

**Comment by licht1stein** [comment]
It works in the most recent version, finally. Closing the issue and thanks for all the input.
