### ISSUE TITLE
Broke by `Fig`

### ISSUE THREAD

**Issue by albert-ying** [Jean-Tinland/simple-bar#273]
After installing [Fig](https://github.com/withfig/autocomplete), everything seems broken (seem that it is because there is a prefix `]697;DoneSourcing` being added for each output?

<img width="261" alt="image" src="https://user-images.githubusercontent.com/59846322/152842810-dce646b1-94ab-4360-a52f-7a0ebd0ac8e6.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/59846322/152842870-83a431be-9cb6-436e-8b9a-a1e258677230.png">

**Comment by Jean-Tinland** [comment]
I saw that indeed, I've been able to skip this issue by not loading my path env in Übersicht but this might cause other issues depending on your setup...
