### ISSUE TITLE
Spaces widget not working after yabai 4.0 upgrade

### ISSUE THREAD

**Issue by theurgi** [Jean-Tinland/simple-bar#278]
macOS Catalina 10.15.7
Ubersicht 1.6

---

After upgrading to yabai 4.0, when I launch Ubersicht I see the following displayed in place of the spaces widget:

![image](https://user-images.githubusercontent.com/58859663/159752288-4b13f9ac-3438-4aee-90f1-7f65ac1982d3.png)

The data widget works as normal.

**Comment by Jean-Tinland** [comment]
Hi! It seems that you are running an old version of simple-bar, can you try to pull the latest commit and restart Übersicht?

**Comment by theurgi** [comment]
Awesome, that did the trick, thanks!
