### ISSUE TITLE
Missing Spaces randomly

### ISSUE THREAD

**Issue by vod3** [Jean-Tinland/simple-bar#28]
First of all, the bar has a great UX!

But sometimes the spaces disappear, after switching workspaces or creating new windows.
Whats the best way to debug this?

Thanks!

**Comment by Jean-Tinland** [comment]
Thanks! Glad that it pleases you!

I think this is a problem related to some yabai commands that are failing on widget refresh. I'll try to reproduce the issue and reduce their occurrences and I'll get back soon to you here.

**Comment by Jean-Tinland** [comment]
I think I've considerably improved the display robustness of the spaces widget with my latest commits.

I'll close this issue for now, feel free to open it again if necessary.
