### ISSUE TITLE
Theme name change from CodingInSylens to just Sylens

### ISSUE THREAD

**Issue by Sylenss** [Jean-Tinland/simple-bar#281]
Hello there jean, its me again I was wondering if I can request a theme name change from CodingInSylens to Sylens.

**Comment by Jean-Tinland** [comment]
Hi! I renamed you theme as requested. You may need to set it again in the settings module.

**Comment by Sylenss** [comment]
Thank you so much jean! I just saw the name change update when I select the theme.
