### ISSUE TITLE
[New Feature Request] Setting for 12/24 Hour Clock

### ISSUE THREAD

**Issue by BMonsalvatge** [Jean-Tinland/simple-bar#284]
It would be nice to have a setting for a 12 or 24 hour clock for the time widget.

**Comment by HellsCrimson** [comment]
It is already there, in the Time settings
<img width="628" alt="Screenshot 2022-05-03 at 17 56 43" src="https://user-images.githubusercontent.com/68403576/166502227-df9f6678-096e-4ce7-85af-37f074ee3daa.png">

**Comment by BMonsalvatge** [comment]
Thanks, I didn't realize there was more to the pane:
![image](https://user-images.githubusercontent.com/1095871/166506519-09aa3efc-9580-4a22-8a36-331502ad2827.png)
