### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by hhemied** [Jean-Tinland/simple-bar#287]
I can't access the website.
![Screenshot 2022-05-15 at 19 38 06](https://user-images.githubusercontent.com/12847532/168487137-ee57e22b-2dbf-49f3-8162-3a9c9bb681ec.png)

It is down for me

**Comment by Jean-Tinland** [comment]
Hi, I had to put it down some months ago as I try to reduce my domain name costs! I plan to make it available again as a GitHub page :)

**Comment by Jean-Tinland** [comment]
I made the website available again here : https://jean-tinland.github.io/simple-bar-website/ :)
