### ISSUE TITLE
Mic/input widet

### ISSUE THREAD

**Issue by izifortune** [Jean-Tinland/simple-bar#29]
Hi,

I've added a widget to display the current input volume.

You can check the component here: https://github.com/izifortune/simple-bar/blob/master/lib/components/Mic.jsx

I'm happy to share and create a PR if you are interested into adding it

**Comment by Jean-Tinland** [comment]
Hi,

Thank for using simple-bar!

I'd be glad to implement it. I'm currently working on a Settings module that would let user choose what widget to display.
I'm working on many files in the project so It would be simpler for you to create a PR now which will be included in my next commits. Doing so I will also add this widget in the Settings module.

Thank you for your work.

**Comment by izifortune** [comment]
Hi @Jean-Tinland thank you for the great work here. I've created a PR here: #29.
I would appreciate if you can label the PR as hacktoberfest-accepted.

Moreover if you want to share any details of your vision for simple-bar I will be happy to help.

**Comment by Jean-Tinland** [comment]
Thank you for this widget, I'm merging it soon.

And thank you for your proposal, I currently doesn't really have a long term vision of this project. I'm simply implementing some new little features for time to time.

The main goal is to keep it simple as it is named "simple-bar" :)
