### ISSUE TITLE
Background for widgets and spaces 

### ISSUE THREAD

**Issue by Sylenss** [Jean-Tinland/simple-bar#291]
Hello, Jean its me again. If i remember correctly it was an option to choose the color between the widgets and the spaces now it seems like its grouped together? Is it possible to change it back?

https://user-images.githubusercontent.com/45975952/171723228-713c26f5-f5ab-4367-ab45-ec64e24e43a4.mp4

**Comment by Jean-Tinland** [comment]
This is indeed a bug added when I merged all simple-bar's widgets together. I will fix it soon. :)

**Comment by Jean-Tinland** [comment]
This should be fixed in the latest commit :)

**Comment by Sylenss** [comment]
Thank you so much
