### ISSUE TITLE
Multi monitor top offset gap

### ISSUE THREAD

**Issue by rchrdw** [Jean-Tinland/simple-bar#297]
I'm having an issue where the bar is aligned with the menu bar for either the built in display or the external monitor, not both. 

When the widget is top aligned to the menu bar with the built in display, there is a gap between the menu bar and the menu bar on the external display. If I refresh the widget from the external monitor, it is aligned with the menu bar on the external but goes into and behind the menu bar on the built in display.

How do I configure the alignment on both the built in display and external monitor so that they are both aligned with the menu bar?

**Comment by Jean-Tinland** [comment]
I'll have to make some tests with an external monitor, I'll keep you updated soon!

**Comment by emilehiot** [comment]
Hello,

I'm sorry to resurrect this old post, but I am encountering the exact same issue with simple-bar not being detected on my external screen connected to my MacBook Pro M2. Have you found a solution since?

Thank you in advance.
