### ISSUE TITLE
Hide Wi-Fi widget when disabled

### ISSUE THREAD

**Issue by cybardev** [Jean-Tinland/simple-bar#299]
Is there a way to hide the wi-fi widget when wi-fi is disabled?  
If not, how would I go about adding it?

And maybe consider adding a checkbox toggle in the settings for the official release?

**Comment by Jean-Tinland** [comment]
I added an option doing exactly that in the latest commit.

**Comment by cybardev** [comment]
Thank you very much. Works just like I wanted. 😊
