### ISSUE TITLE
Can't interact with the simple-bar at all

### ISSUE THREAD

**Issue by WarpWing** [Jean-Tinland/simple-bar#3]
Hi! So after Installing Ubersicht and disabling SIP, I can't interact with the bar at all. Could I get some assistance because I really like all the features <3

**Comment by Jean-Tinland** [comment]
Hi,

In order to interact with Ubersicht widgets, make sure you selected an "Interaction shortcut" in Ubersicht settings:
<img width="417" alt="Screenshot 2020-07-11 at 09 23 09" src="https://user-images.githubusercontent.com/43068795/87219083-ade18d80-c358-11ea-8704-7f7b102e70c6.png">
<img width="605" alt="Screenshot 2020-07-11 at 09 23 27" src="https://user-images.githubusercontent.com/43068795/87219087-b5a13200-c358-11ea-892d-34aa894e3aaf.png">

You'll need to click with this shortcut pressed to toggle wifi on/off, go to or add spaces.

Let me know if that solves your problem.

Thank you for the interest you shown for the project. :)

**Comment by WarpWing** [comment]
Thank you for taking the time to write back to me! I am happy to report that this solution works! Thank you once again for bringing such a well-developed project to Github :)

**Comment by WarpWing** [comment]
Actually and I hate to bother you again. I kinda of got the simple bar working with that fix. However, when I tried to make the 
bar dynamic with

yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=display_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'" 

It didn't update the bar dynamically (this was after reloading yabai in homebrew) and it broke my shortcut to interact with the bar. Any idea how to fix it?

**Comment by WarpWing** [comment]
Actually, update. Executing the .yabairc actually saw the dynamic update and it registers when I switch back and forth in between tabs (just had to update config). However, it won't register my click whenever I use my shortcut to interact with the bar

**Comment by Jean-Tinland** [comment]
That's strange...

The easiest way to use Yabai is to let Homebrew handle it:
```bash
brew services start koekeishiya/formulae/yabai
```

Doing that, Homebrew will start Yabai on computer startup and keep it running in background.

About these 3 lines:
```bash
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=display_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
```

They should be added manually in your .yabairc:
```bash
vi ~/.yabairc
```

Here is my .yabairc as an example:
```bash
#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Roboto:Regular:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff1B222D
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10 11 12
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmot                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.16
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset # exterior
yabai -m config window_border_width          5
yabai -m config window_border_radius         3
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xffF9D48F
yabai -m config normal_window_border_color   0xff1B222D
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  48
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=display_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-2-jsx\"'"

yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="Colorpicker" app="^Colorpicker$" manage=off
yabai -m rule --add label="iTerm2" app="^iTerm2$" manage=off

echo "yabai configuration loaded.."
```

Each time you update this config file, you'll need to restart Yabai so that the changes can be taken into account.

Restart Yabai with:
```bash
brew services restart koekeishiya/formulae/yabai
```

Try to follow these steps, It may solve your problem.

**Comment by WarpWing** [comment]
After some tinkering with yabai
https://github.com/WarpWing/Sentinel/blob/master/.yabairc
I was able to get the interaction between the bar and I working again. The bar won't dynamically register the icons and new workspaces though

**Comment by WarpWing** [comment]
Actually, I'm pretty happy with how it is now. The dynamic workspaces don't really matter much to be. Thanks for the long term support though :D

**Comment by Jean-Tinland** [comment]
I've just made a new update of simple-bar that include a better handling of window creation and focus change.

You'll need to pull the last version & to add some signals to your .yabairc :

```sh
# Refresh spaces widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh spaces widget on display focus change
yabai -m signal --add event=display_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh process widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Uncomment next line to enable spaces widget refresh on your 2nd monitor
# yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-2-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
```

This update also include the possibility (with SIP disable) to destroy spaces by clicking first on the bin then by clicking on a specific space.

**Comment by WarpWing** [comment]
Thanks! It turns out that Ubersicht didn't have access to something so I turned it on and it works! I'll make sure to pull yabai and update you if it works :)
