### ISSUE TITLE
"Right side of assignment cannot be destructured"

### ISSUE THREAD

**Issue by zsbrown97** [Jean-Tinland/simple-bar#300]
I just installed and activated this widget in Ubersicht, and when I'm on my laptop screen it appears and functions just fine. But whenever I focus on a new display (I currently run a 2019 Macbook Pro as my main display, with an additional monitor and my iPad Pro using Sidecar), I get a warning on my main display that won't go away until I focus back on the main display:

<img width="761" alt="Screen Shot 2022-07-05 at 12 38 21 PM" src="https://user-images.githubusercontent.com/51924558/177384942-ebf08a55-cf85-48d7-b456-e35e9817915d.png">

As I said, this was just installed and activated, with no other additions or modifications. Any ideas?

**Comment by jinh0** [comment]
Having this same issue! Just installed and activated simple-bar as well, and this exact issue happens when I move between two different monitors.

**Comment by CaidanS** [comment]
+1 to this, running on M1 Pro, I only have an issue on exterior monitor. The monitor does work on my 2015 Pro.

**Comment by SatouKuzuma1** [comment]
Same problem here! With the intel processor.

**Comment by slesaad** [comment]
I have the same problem too!

**Comment by jones-sam** [comment]
same problem here with m1

**Comment by Jean-Tinland** [comment]
My bad! It seems that I created a bug while fixing another one! This will be corrected soon!

**Comment by Jean-Tinland** [comment]
This should be fixed now :)
