### ISSUE TITLE
Spaces not working on m1 Mac, SPI is disabled

### ISSUE THREAD

**Issue by timoteicioaba** [Jean-Tinland/simple-bar#302]
error on yabai terminal:
`Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx".`

**Comment by Gitmaster511** [comment]
Check my Pull request. That solved all my errors on m1 macs

**Comment by Jean-Tinland** [comment]
Hi, the issue related to this message `Übersicht got an error: Can’t get widget id "simple-bar-spaces-jsx".` should be resolved in the latest commit.

As for your other errors I don't know what is happening for now as I don't own a m1 mac...

**Comment by timoteicioaba** [comment]
Thank you anyway, if someone with an m1 mac has solved this problem, let me know. Cheers!
