### ISSUE TITLE
Add support for OpenVPN/Nord/Express

### ISSUE THREAD

**Issue by Gitmaster511** [Jean-Tinland/simple-bar#306]
Viscosity VPN(what is supported right now) is only free for 30 days. It would make more sense to use support OpenVPN or some popular clients directly like Nord, Express and Proton.

**Comment by Jean-Tinland** [comment]
Hi! As I'm not a VPN user myself, the Viscosity VPN functionality has been added via pull request.
I'd be glad to merge some others If anyone wants to contribute but I'm not planning on doing it myself.

**Comment by Jean-Tinland** [comment]
I'm closing this issue as I can't work on this on my end. As I said, if anyone is providing a working pull request, I will merge it if I feel in can maintain it on the long run.
