### ISSUE TITLE
Custom styling for user widgets

### ISSUE THREAD

**Issue by itaysharir** [Jean-Tinland/simple-bar#311]
How can i change things like the background color for a user created widget? Can i do that in the custom styling tab? How should i refer to the the widget i created in CSS? 
Thanks in advance!

**Comment by Jean-Tinland** [comment]
Each custom widget has its own custom class name based on its order, for example: `user-widget--0`.

So if you want to apply a specific background color to your second custom widget, you can use this css selector in the custom styling tab:

```css
.user-widget--1 {
  background-color: blue;
}
```

**Comment by itaysharir** [comment]
![Screen Shot 2022-08-14 at 14 07 29](https://user-images.githubusercontent.com/87126382/184533984-a54fcf76-93f4-4f45-b833-405a4b1433ec.jpg)

**Comment by itaysharir** [comment]
Why does this not work?
