### ISSUE TITLE
Does simple-bar support linux? Hope to use it in linux with i3 window manager

### ISSUE THREAD

**Issue by themysteryboy** [Jean-Tinland/simple-bar#313]

**Comment by Jean-Tinland** [comment]
Hi! As I suggested an other user in #7 you can take a look at [this link](https://www.reddit.com/r/unixporn/comments/j4he3v/bspwm_blossom/): someone recreated the look & feel of simple-bar for polybar!

I hope this will help you :)

**Comment by themysteryboy** [comment]
Thanks a lot for your help
