### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by shot-codes** [Jean-Tinland/simple-bar#314]
What are peoples experience with power consumption. I'm seeing around a 4,0 in 12h power in activity monitor which seems a little high. Perhaps this is expected with a full blown node server constantly running but I figured I would here what others experience was and If my case is unusually high.

**Comment by Jean-Tinland** [comment]
I don't know for others but it is certain that simple-bar has an impact on the battery lifespan as it is running some sort of Safari webview on the desktop (Übersicht) + executing queries with yabai each time you switch space/app.

On top of that depending of the number of data widgets you enabled and their refresh frequencies you set there can be an additional battery discharge.
