### ISSUE TITLE
No colors in data not working

### ISSUE THREAD

**Issue by williamhCode** [Jean-Tinland/simple-bar#323]
I have no colors in data enabled, but there's still colors in data. I also tried restarting the widget but it didn't help. Anyone else also has this issue?
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/83525937/197925545-ac809b8c-fd87-44cc-897e-00c7a4584f46.png">

macOS version = 12.6, macbook pro 13 m1

**Comment by Jean-Tinland** [comment]
I'll look into it soon, this must be a bug introduced when I merged the several Übesicht widgets composing simple-bar into one.

**Comment by n3ph** [comment]
@Jean-Tinland Pr fising the bug:
- https://github.com/Jean-Tinland/simple-bar/pull/337
