### ISSUE TITLE
simple-bar website is down

### ISSUE THREAD

**Issue by azinsharaf** [Jean-Tinland/simple-bar#326]
the website in About section is down
https://www.jeantinland.com/toolbox/simple-bar

**Comment by Jean-Tinland** [comment]
Indeed, I'm rewriting this part of my website and I forgot to add a message. I also updated the url in the "About" section!

Thanks for the report!

**Comment by azinsharaf** [comment]
Thanks.

**Comment by Jean-Tinland** [comment]
The landing page is back online! :)
