### ISSUE TITLE
simple-bar-index.jsx: Something went wrong... error when trying to load simple bar

### ISSUE THREAD

**Issue by dhr-uvin** [Jean-Tinland/simple-bar#329]
I disabled SIP on my system and now simple bar does not work. Even after re-enabling it it still pops the error "simple-bar-index.jsx: Something went wrong..." . How can I fix this? Its extremely irritating as I love simple bar.

**Comment by bashu** [comment]
same...

**Comment by bashu** [comment]
oh, nevermind. I have yabai installed via macports, and it's located at /opt/local/bin

**Comment by Jean-Tinland** [comment]
Hi @dhr-uvin, like bashu can you check what is the output of this command?
```shell
which yabai
```
This message can be displayed when you yabai path is not the (arbitrary) default one. You can get your yabai path and set it in the settings module.

**Comment by dhr-uvin** [comment]
Hey @Jean-Tinland , thanks for the response. Im going to close this issue since I kind of messed up my whole macos install and reinstalled regardless. It works now. Thanks.
