### ISSUE TITLE
[Enhancement] Taskwarrior/todolist integration

### ISSUE THREAD

**Issue by yushangakki** [Jean-Tinland/simple-bar#33]
This bar is great! However, could someone help to integrate task-warrior into it? Thanks!

For reference here is one for built-in menubar: https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/taskwarrior.4m.py

**Comment by Jean-Tinland** [comment]
Hi, thank you for the compliment!

I'm not familiar enough with task-warrior to apprehend correctly this problematic and offer a proper solution. I'll leave this issue open with a "help wanted" label in case someone else can you give a hand on this.

**Comment by Jean-Tinland** [comment]
I'll close this for now. If more people show interest in this and I someone give a hand it will be if course reopened. :)
