### ISSUE TITLE
Spaces dont fully work with SIP disabled completly (Macbook Air M1 2020)

### ISSUE THREAD

**Issue by DragonDev07** [Jean-Tinland/simple-bar#331]
When I click on a Space, it doesn't switch spaces, it also doesn't add a space when I hit the plus button. I have tried checking the Yabai path, but other than that haven't done any further research.

**Comment by IsaccBarker** [comment]
> ... haven't done any further research.

Check the README Teo.

**Comment by DragonDev07** [comment]
Realised it's due to yabai being unable to load scripting addition
