### ISSUE TITLE
Spotify Play/Pause icon

### ISSUE THREAD

**Issue by azinsharaf** [Jean-Tinland/simple-bar#332]
Thanks for this great widget. I can't work without it.

regarding Spotify widget, i think the widget icon (play and pause) should be visa versa.  Currently when Spotify **is playing** the icon is:
 
![image](https://user-images.githubusercontent.com/10101468/207165066-80bb307f-6ebc-440e-9702-06558c1b20bc.png)

All of the players will show Pause icon when they are playing so when we click it would pause the song.

![image](https://user-images.githubusercontent.com/10101468/207165420-aec74a33-f42a-44a0-905d-6276842c9869.png)

**Comment by gldtn** [comment]
Totally agree, it got me confused for a bit lol.

**Comment by Kn4ughty** [comment]
Should be fixed now
