### ISSUE TITLE
settings window opening behind other windows

### ISSUE THREAD

**Issue by davelongdev** [Jean-Tinland/simple-bar#339]
hi.  when i open simple-bar settings, the window always opens behind any other windows that are open.  anyone know how to bring it to the front?  anyone else have this issue?  maybe it's a yabai setting?

thanks

**Comment by Kn4ughty** [comment]
I did some research about Ubersicht and I don't think it's currently possible with how its rendering is done. 
[this issue](https://github.com/felixhageloh/uebersicht/issues/97)
