### ISSUE TITLE
M1 Macbook Pro

### ISSUE THREAD

**Issue by alexgulbrandsen** [Jean-Tinland/simple-bar#340]
Hello!
I´ve installed Ubersicht, but the bar does not seem to load. What am I doing wrong ?

**Comment by Kn4ughty** [comment]
Hello, 
Some more information could be good, have you put the widget inside your Ubersicht folder?
(Accessible by clicking on Ubersicht in the menu bar (Open Widets folder) or the path `/Users/school/Library/Application Support/Übersicht/widgets`)
Also, make sure the widget is enabled in the Ubersicht menu.

**Comment by alexgulbrandsen** [comment]
I´ve got it to work now :) just need to take it on top of the screen also. Is there a solution for the notch ?

**Comment by Kn4ughty** [comment]
Ah nice I'm glad you got it to work.
Regarding the notch, in the settings, you can turn off the centred process widget in the process panel if that is what you mean.
