### ISSUE TITLE
No idea why it's broken - clean install, Mojave

### ISSUE THREAD

**Issue by arisolt** [Jean-Tinland/simple-bar#342]
Hi, 

I've just installed Übersicht and then simple-bar. Something is very wrong, and I have no idea why. Specs:

Mojave
yabai 3.3.10
Übersicht 1.6

I'm attaching a screenshot of what simple-bar currently looks like on my screen

<img width="1126" alt="Screenshot 2023-03-27 at 05 02 35" src="https://user-images.githubusercontent.com/2144830/227837897-4ee0fd65-8527-4380-bc07-70b21faa0342.png">

Can anyone help me troubleshoot this please?

**Comment by Jean-Tinland** [comment]
It's been a long time since I upgraded from Mojave so I won't be able to look for the cause of this problem. 
You could try to checkout the git repo to an older commit and try to see if this problem is still occurring.
