### ISSUE TITLE
Xcode process is not showing

### ISSUE THREAD

**Issue by arorashivoy** [Jean-Tinland/simple-bar#345]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/85881270/230795479-e3c914a0-46e6-4a75-a4fa-91d4773a7793.png">

Like in the photo above xcode process is not showing in the status bar, like it shows in the example below

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/85881270/230795523-f1b0fa99-cd6e-435d-ad8a-a0d7dda4c8e1.png">

**Comment by Jean-Tinland** [comment]
I'm closing this as I think it is a configuration bug, feel free to open a new issue if you encounter the same problem.
