### ISSUE TITLE
Refresh on Yabai restart

### ISSUE THREAD

**Issue by exic** [Jean-Tinland/simple-bar#356]
Is there an easy way (cli command?) to refresh the bar when I restart Yabai? It seems frozen on every restart so I have to click "Refresh All Widgets" to get it working again.

Probably something like this 🤔 ? https://github.com/Jean-Tinland/simple-bar/issues/50#issuecomment-720100579

**Comment by Jean-Tinland** [comment]
Yes, you can add this line in your .yabairc:
```shell
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'
```
This will automatically do the same as clicking on "Refresh all widgets" in the Übersicht menu.
Let me know if this solves your problem!

**Comment by exic** [comment]
It does perfectly, thank you!
