### ISSUE TITLE
Bar position

### ISSUE THREAD

**Issue by vod3** [Jean-Tinland/simple-bar#36]
Hey,
the new settings look good, another idea for an option would be to define the bar position, for example [ ] - Top [ ] -Bottom.
What do you think?
This would include the Popup which moves or delete Spaces.

**Comment by Jean-Tinland** [comment]
Thanks! This is a good suggestion, I'll add it soon.

I'll keep you updated here once its done.

**Comment by Jean-Tinland** [comment]
I've just added a "Bottom bar" option in settings.
