### ISSUE TITLE
simple-bar correctly alligned on one monitor, not both

### ISSUE THREAD

**Issue by rwijtvliet** [Jean-Tinland/simple-bar#362]
I'll just continue filing bug reports until I find one that's actually a real issue ;)

I have connected an external display, and the simple-bar bar is not showing correctly on one of them.

* If I click `übersicht` --> refresh all widgets on the built-in monitor, that monitor's bar is looking good...
  ![image](https://github.com/Jean-Tinland/simple-bar/assets/4106013/52585ba0-e5a6-40e3-990b-9a907bda558f)
  ...but there is a gap between the menu bar and the simple-bar bar on the external monitor:
  ![image](https://github.com/Jean-Tinland/simple-bar/assets/4106013/852b19a5-fc77-4e4b-84dd-c2c0eef11acd)

* If I do the same on the external monitor, it looks good there...
  ![image](https://github.com/Jean-Tinland/simple-bar/assets/4106013/80c67a7a-9900-4c4e-b1ca-c9a6a28372c5)
  ...but on the external monitor, the simple-bar bar is partially hidden behind the menu bar:
  ![image](https://github.com/Jean-Tinland/simple-bar/assets/4106013/a398167d-7a95-43b6-acfe-c7eaf214ee58)

I didn't find any setting to change this.

**Comment by emilehiot** [comment]
Solution : https://github.com/Jean-Tinland/simple-bar/issues/360

**Comment by rwijtvliet** [comment]
Hey Emile,

I had seen that issue, but I don't think it's applicable here. There, it is described how to add a buffer for the bar to each space. But I don't see how to change the position of the bar to always be directly below the menu bar, nor how to make the distance dependent on the *display* (instead of the space).

Let me know if I'm mistaken!

**Comment by rwijtvliet** [comment]
I think the issue is caused by the fact that the menu bar on the built-in monitor is drawn taller than on the external monitor. If you compare the images in each set, the distance between the top of the screen and the top of the simple-bar is very similar.

**Comment by Jean-Tinland** [comment]
I think I should be resolved as stated in #372 with a fix in Übersicht.

Feel free to open a new issue if you still have this issue.
