### ISSUE TITLE
Simple Bar no longer draws at top of screen

### ISSUE THREAD

**Issue by beezu** [Jean-Tinland/simple-bar#372]
Hardware - M2 Macbook Pro 16"

After updating my Mac to Mac OS Sonoma 14.1, simple bar no longer draws at the very top of my screen. I have my Mac's menu bar set to always hide, and before the update, simple bar drew at the very top of the screen. After the update, it now draws starting at the bottom of where the menu bar would normally end if it weren't hidden. This happens on both the built-in monitor and external monitors.

Image of simple bar:
<img width="460" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/28872452/02dff8b8-c589-445e-ad9b-14bf02423683">

Image of the bar when hovering the built-in menubar:
<img width="428" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/28872452/b75754b2-ac2a-451e-b5dd-a756bc8451cd">

**Comment by Jean-Tinland** [comment]
I think this issue is comming from Übersicht and is almost already fixed
See this issue in the Übersicht repo: https://github.com/felixhageloh/uebersicht/issues/517.

**Comment by HeySora** [comment]
For anyone impacted by this issue, it has been solved in a newer build of Übersicht, downloadable there: https://tracesof.net/uebersicht/releases/Uebersicht-1.6.80.app.zip

(Original comment: https://github.com/felixhageloh/uebersicht/issues/517#issuecomment-1818437723)
