### ISSUE TITLE
The Arc icon has malformed SVG

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#374]
The Übersicht console shows this error:

![image](https://github.com/Jean-Tinland/simple-bar/assets/17962248/3e20ca8d-a7d9-45fd-af3f-f65b08aae52e)

Which is precisely coming from this path in Arc's icon, introduced in 39f0ea8
https://github.com/Jean-Tinland/simple-bar/blob/1e2651346e2d52bc5e904fcf54df4cd2fa54be85/lib/components/icons.jsx#L1422-L1426

Looking at it, some parts of it indeed look "too" minified, such as `2.04s.026.053.101.16c.083.118.202.268.362.444a9.28` for example, and the sequences of 6-7 whitespaces in a row a bit later in the line further indicate that something went wrong while adding that icon.

Here is how Arc's icon looks like, for reference:

![image](https://github.com/Jean-Tinland/simple-bar/assets/17962248/a89e693d-fc21-46ae-a404-56482132ea91)

**Comment by Jean-Tinland** [comment]
Indeed, I added a new version of the icon that seems to work fine. Let me know if the design is ok!

Thanks :)

**Comment by HeySora** [comment]
Looks perfect, and there's no more errors! Thank you so much ❤️
