### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by vod3** [Jean-Tinland/simple-bar#38]
Im working a lot with Blender, iTerm2 and Affinity Products (Photo, Designer, Publisher).
Any chance of getting the additional appicons integrated in the windowswitcher?

Thanks!

**Comment by MikoMagni** [comment]
@vod3 the iTerm2 icon is already in simple-bar

You need to remove iTerm2 from the exclusions.

Open Space.jsx and look for 

```const EXCLUSIONS = ['Finder', 'iTerm2', 'Hyper']```

remove iTerm2

```const EXCLUSIONS = ['Finder', 'Hyper']```


<img width="128" alt="image" src="https://user-images.githubusercontent.com/2527231/95938085-aed6ff00-0e20-11eb-8963-78792fa78c9b.png">

**Comment by MikoMagni** [comment]
I started a PR with all Affinity Icons. You can view a screnshot here:
https://github.com/Jean-Tinland/simple-bar/pull/39

**Comment by Jean-Tinland** [comment]
Thanks Miko!

I'll soon move exclusions in settings. It will be more practical for everyone.

**Comment by MikoMagni** [comment]
Good idea!

**Comment by Jean-Tinland** [comment]
I also added Blender icon.

**Comment by christo-ph** [comment]
When trying to add some Icons, I am always struggling with the SVG I get from Illustrator, Inkscape or downloaded SVGs, as they are quite complex SVGs.

Whats tools do you use, what's the best way to create clean icons, preferably resulting in a simple

`<path d='...' />`

Thanks
