### ISSUE TITLE
simple-bar-index.jsx: Something went wrong...

### ISSUE THREAD

**Issue by nendix** [Jean-Tinland/simple-bar#384]
I get this error when I try to load simple bar, I've already changed the yabaiPath in the settings module, how can I fix that?

**Comment by Jean-Tinland** [comment]
What are your OS, yabai and Übersicht versions please?

You can try to follow theses steps.

First make sure that you have started yabai with:

```shell
yabai --start-service
```

You should put in the settings module the output of this command:

```shell
which yabai
```

If yabai services are started and you put the right path in simple-bar' settings module, can you try to run this command and see if the json output is broken in anyway?

```shell
# go to simple-bar folder
cd $HOME/Library/Application\ Support/Übersicht/widgets/simple-bar

# manually run the init.sh script (which is run on every simple-bar refresh) with all arguments to false except yabai path
bash ./lib/scripts/init.sh $(which yabai) "false" "false" "false"
# 1st argument = yabai_path
# 2nd argument = display_skhd_mode
# 3rd argument = disable_signals
# 4th argument = enable_window_title_changed_signal
```

Better, if you have `jq` installed, you can check directly if the output is valid by piping the result of the command through it:

```shell
bash ./lib/scripts/init.sh $(which yabai) "false" "false" "false" | jq
```

Please let me know these information are useful :)

**Comment by nendix** [comment]
thank you for the infos, I fixed it
