### ISSUE TITLE
Question: Process name for all processes in active space

### ISSUE THREAD

**Issue by JustSaX** [Jean-Tinland/simple-bar#390]
Is it possible to have the process names for all processes in the active space? Instead of having only the process name of the active window and symbols for all other processes.

Example (active window in **bold**):
Now:  symbol | symbol | **terminal** | symbol
Would like to have: firefox | terminal | **terminal** | vscode

Thanks for your help!

**Comment by Jean-Tinland** [comment]
I added a new setting (defaults to `false`): "Expand all processes". It forces open all processes. The current one is highlighted as before.

![image](https://github.com/Jean-Tinland/simple-bar/assets/43068795/8ad90034-fce4-4800-b4fa-b01dae6439ea)

Let met know if this is what you had in mind.
