### ISSUE TITLE
Spaces and app icons is not working

### ISSUE THREAD

**Issue by alexgulbrandsen** [Jean-Tinland/simple-bar#395]
**Describe the bug**

**To Reproduce**

3. See error

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**

- OS Sonoma 14.4.1
- yabai-v6.0.0
- Übersicht version  1.6

**Additional context**
Hello. I am having a problem where the icons and spaces is not working properly when changing spaces.

**Comment by shuumo** [comment]
simple workaround is just to symlink yabai to /usr/local/bin/yabai (i have yabai installed to /opt/homebrew/bin/yabai). Or slightly more effortful way is to go through all the jsx files and change the yabai path, as its hardcoded in a few spots i believe.

**Comment by Jean-Tinland** [comment]
@shuumo this would indeed work but I also implemented a settings allowing to change yabai path in a proper way in the settings module (it can be opened by clicking first on simple-bar then by pressing `cmd`+`,`.

![yabai-path](https://github.com/Jean-Tinland/simple-bar/assets/43068795/e0fff14c-ba59-4feb-bef3-9b685ee1906e)
