### ISSUE TITLE
WhatsApp icon not being used

### ISSUE THREAD

**Issue by haxybaxy** [Jean-Tinland/simple-bar#405]
The WhatsApp icon is not showing up, even though it is included in the icons folder. 

<img width="327" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/87573953/4f4c460f-b3fc-457b-8f22-8541dd6f767c">*

- OS version Sonoma 14.5
- Yabai version 7.1.1
- Übersicht Version 1.6 (82)

**Comment by mrala** [comment]
It looks like there is an invisible unicode character (U+200E) in the name of the app. Try copying and pasting this `"‎WhatsApp"` to `lib/app-icons.js`:

<img width="441" alt="Screenshot 2024-06-24 at 12 30 56" src="https://github.com/Jean-Tinland/simple-bar/assets/4516025/3b9eb2af-7b8f-4234-9d82-2153f0b93fa6">

<img width="61" alt="Screenshot 2024-06-24 at 12 32 13" src="https://github.com/Jean-Tinland/simple-bar/assets/4516025/fb650449-c747-4c0b-9077-c73af36c54ea">

**Comment by haxybaxy** [comment]
Works perfectly!
