### ISSUE TITLE
Can't see bar when I import something into index.jsx

### ISSUE THREAD

**Issue by haxybaxy** [Jean-Tinland/simple-bar#411]
I am trying to add a tiny SVG icon to the left of the spaces component, so I made a component in a separate file to hold the icon, but whenever I import a file into the index.jsx file the bar will stop rendering.

I can add the SVG directly into the index file and it works, but I wanted to put it in a different file because it would be tidier this way, and it could be a nice feature to add officially since lots of sketchybar features have this.

1. Create a new file that returns and SVG component like this:
```
import React from 'react';

const MyIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="currentColor"
    width="24px"
    height="24px"
  >
    <path d="M12 2C8.13 2 5 5.13 5 9c0 3.87 3.13 7 7 7s7-3.13 7-7c0-3.87-3.13-7-7-7zm0 12c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm-1-8h2v4h-2V6zm0 6h2v2h-2v-2z"/>
  </svg>
);

export default MyIcon; 

```
2. Import the folder into index.jsx like so: 
`import MyIcon from "./lib/components/sideicon.jsx";`
3. Refresh widgets from Übersicht

This is the error I am getting in the debug console:
<img width="1127" alt="Screenshot 2024-07-16 at 23 22 43" src="https://github.com/user-attachments/assets/69833ef4-1d6a-4ae5-90ca-a22a04f14475">

- Mac OS Sonoma 14.5
- Yabai version 7.1.1
- Übersicht version 1.6

**Comment by Jean-Tinland** [comment]
I think this is simply due to the way you import React in your component. With Übersicht, you have to import React like this:

```javascript
import * as Uebersicht from "uebersicht";
const { React } = Uebersicht;
```

Please let me know if this solves your issue!

**Comment by haxybaxy** [comment]
It does solve the issue! Thank you so much!
