### ISSUE TITLE
Floating app icons (e.g. MSTeams) shown on all spaces

### ISSUE THREAD

**Issue by kyoshiro** [Jean-Tinland/simple-bar#414]
**Description**
Running MSTeams for example on MacOS lists its icon in simple-bar on all spaces, see screenshot below.

The MSTeams icon and - if running - the meeting icon (second app-icon) will be shown for all spaces. This will reduce available space in simple-bar significantly, so status-icons may run out of screen on the righthand side, eg. clock, date.

**To Reproduce**

1. Open MSTeams app
2. See described issue in status-bar

**Expected behavior**
The icons for MSTeams should only be shown for the spaces the application is running currently.

**Screenshots**
<img width="632" alt="image" src="https://github.com/user-attachments/assets/5d0ca18e-b7d0-49d5-b79a-e95de649b06b">

**Information (please complete the following information):**

- OS version [Sonoma 14.6]
- Yabai version [yabai-v7.1.1] (output of `yabai --version`)
- Übersicht version [Version 1.6 (82)]

**Comment by kyoshiro** [comment]
In addition, this seems to be related to apps, which may be shown on all spaces, means, they move with your focus between spaces, e.g. nagstamon (non-specific app icon) also will be shown on all spaces, because the app will follow the focused space.

Because "eating" space significantly there should be an option to "hide" these apps, because they will be open anyway and there is no need to indicate where/on which spaces they are running.

**Comment by kyoshiro** [comment]
Okay, I found out, there is the option to ignore Apps by its name. This works for e.g. nagstamon very well.
I will also try to hide the MS Teams Meeting window from visibility in spaces.

**Comment by kyoshiro** [comment]
For MS Teams it's a bit tricky. Hiding the App by its name will hide it completely, also the main window of MS Teams, which should be listed in spaces. Hiding by window title works somewhat if meetings would be strictly named "Meetings.*" but that's unsafe because meetings can be named freely.

In this case I would suggest hiding floating apps which will be shown on all spaces as mentioned earlier in this issue.

The workaround hiding apps by its name or window title is a good starter already working.

**Comment by Jean-Tinland** [comment]
Can you try to enable the "Display sticky windows separately" in the "Spaces" tab settings?

It should fix this behavior by grouping all "sticky" windows on the left side of the spaces widget.

Please let me know if this solves your issue :)

**Comment by kyoshiro** [comment]
@Jean-Tinland Thx, that's great. I will close this issue now.
