### ISSUE TITLE
Netstats without graph

### ISSUE THREAD

**Issue by ai4bing** [Jean-Tinland/simple-bar#416]
**Describe the bug**

When `Display as graph` is unchecked under __Network stats__, Übersicht debug console gives error on refresh, and simple-bar widget disappears.

By switching away and back to `Show on Built-in Retina Display` in Übersicht, widget comes back again.

<details>
  <summary><b>Error in debug console (foreground)</b></summary>

<br>
[Error] The above error occurred in one of your React components:<br>
&nbsp;&nbsp;&nbsp;&nbsp;in Unknown<br>
&nbsp;&nbsp;&nbsp;&nbsp;in div<br>
&nbsp;&nbsp;&nbsp;&nbsp;in Inner (created by Widget)<br>
&nbsp;&nbsp;&nbsp;&nbsp;in div (created by Widget)<br>
&nbsp;&nbsp;&nbsp;&nbsp;in Widget<br>
&nbsp;&nbsp;&nbsp;&nbsp;in Unknown<br>
&nbsp;&nbsp;&nbsp;&nbsp;in div<br>
&nbsp;&nbsp;&nbsp;&nbsp;in div<br>
&nbsp;&nbsp;&nbsp;&nbsp;in SimpleBarContextProvider
<br>
Consider adding an error boundary to your tree to customize error handling behavior.<br>
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:573223)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;logError (client.js:1:573241)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:590956)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:425915)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commitUpdateQueue (client.js:1:425925)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commitLifeCycles (client.js:1:578825)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commitLayoutEffects (client.js:1:631571)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callCallback (client.js:1:230570)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dispatchEvent<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;invokeGuardedCallbackImpl (client.js:1:230657)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;invokeGuardedCallback (client.js:1:231854)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:625487)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:857894)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commitRoot (client.js:1:622435)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:613110)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;performSyncWorkOnRoot (client.js:1:613117)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:400130)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:857894)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;flushSyncCallbackQueueImpl (client.js:1:400025)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;flushSyncCallbackQueue (client.js:1:399869)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scheduleWork (client.js:1:601923)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dispatchAction (client.js:1:487845)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (simple-bar-index-jsx:1788)<br>
<br>
[Error] Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.<br>
&nbsp;&nbsp;&nbsp;&nbsp;in Unknown<br>
&nbsp;&nbsp;&nbsp;&nbsp;in div<br>
&nbsp;&nbsp;&nbsp;&nbsp;in div<br>
&nbsp;&nbsp;&nbsp;&nbsp;in SimpleBarContextProvider<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printWarning (client.js:1:228280)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;error (client.js:1:227860)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (client.js:1:602889)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scheduleWork (client.js:1:603210)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dispatchAction (client.js:1:487845)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(anonymous function) (simple-bar-index-jsx:1782)
</details>

**Information (please complete the following information):**

- OS version [e.g. Sonoma 14.6]
- Yabai version [e.g. yabai-v7.1.2] (output of `yabai --version`)
- Übersicht version [e.g. Version 1.6 (82)]

**Comment by Jean-Tinland** [comment]
It seems that I introduced a bug in a recent commit. Thank you for reporting this issue!

I just pushed a fix that should correct this behavior.

Please let me know if everything is working as expected on your end.

**Comment by ai4bing** [comment]
It now works, thank you for the really quick fix.
