### ISSUE TITLE
macOS Sequoia Wifi Icon "Searching..." networksetup -getairportnetwork en0 gives "You are not associated with an AirPort network."

### ISSUE THREAD

**Issue by matzegebbe** [Jean-Tinland/simple-bar#421]
**Describe the bug**

<img width="267" alt="image" src="https://github.com/user-attachments/assets/3bfd33de-c1e3-418a-9be8-b0545b697118">

The Wi-Fi icon shows "Searching..." even though a connection is established. This is more of an FYI for other users!

**Where is the error located**

It seems that the command
```
networksetup -getairportnetwork en0
```
on macOS Sequoia 15.0 always returns `You are not associated with an AirPort network.`

**Expected output**

The SSID of the connected network.

**Additional context**

For reference: https://apple.stackexchange.com/questions/475370/networksetup-getairportnetwork-return-you-are-not-associated-with-an-airport-ne

A possible workaround for retrieving the SSID can be this command:

```
system_profiler SPAirPortDataType | awk '/Current Network/ {getline;$1=$1;print $0 | "tr -d ':'";exit}'
```
in this line https://github.com/Jean-Tinland/simple-bar/blob/master/lib/components/data/wifi.jsx#L50

**Comment by Jean-Tinland** [comment]
Thanks! I'll keep that in mind when I upgrade to Sequoia 15.0 and I'll try to implement a fix allowing the network widget to work correctly on all macOS versions.

**Comment by Jean-Tinland** [comment]
Fixed on master!
