### ISSUE TITLE
A lot of "Something went very wrong errors"

### ISSUE THREAD

**Issue by WarpWing** [Jean-Tinland/simple-bar#45]
Hello Jean :D. Good to see this repository is doing well. I'm here because I decided to mess around with my MacOS Rice a little. I decided to reinstall your version of simple-bar rather than a friend's take on it. I see that on the usage of the command 
```bash
git clone https://github.com/Jean-Tinland/simple-bar $HOME/Library/Application\ Support/Übersicht/widgets/simple-bar
``` 
This freaks simple-bar out and I don't know how to solve it
![image](https://user-images.githubusercontent.com/28925758/97017624-26411880-151c-11eb-82a0-468d49d5c627.png)
Thanks in advance for any help you can provide!

**Comment by WarpWing** [comment]
![image](https://user-images.githubusercontent.com/28925758/97022329-fdbc1d00-1521-11eb-8e44-2e849c372e50.png)
Also, I can't interact with the bar like I did the first time. It should be also be worth noting that yabai isn't installed. Is it a requirement?

**Comment by WarpWing** [comment]
Actually, installing Yabai fixed the issue. I'm just a idiot xd.

**Comment by Jean-Tinland** [comment]
Hi, I was indeed thinking about that since the 2 widgets which weren't working were depending on **yabai** to get their data.

No problem, I think I need to cleanup the readme because the "Compatibility & requirements" is a bit lost in the middle of everything.

Glad it is working now!

**Comment by Obl1que** [comment]
This happened to me, but I had yabai installed. I managed to fix it by entering the right yabai path in the cmd + , settings, and upgrading/reinstalling yabai. Works beautifully now. Just wanted to say it for anyone that is having the same problem
