### ISSUE TITLE
Blackbox in Simplebar Render

### ISSUE THREAD

**Issue by WarpWing** [Jean-Tinland/simple-bar#46]
Hello Jean :D Back again in Warp configures his MacOS horribly Part 2! This time, there is a weird black box that now occupies the top left corner of my screen. Any ideas on what could be causing it 

![image](https://user-images.githubusercontent.com/28925758/97063990-fbcd7a80-1570-11eb-9a61-74798076c2bb.png)

**Comment by Jean-Tinland** [comment]
Hi!

That's weird haha, never seen anything like this. Have you tried to inspect it with the Übersicht debug console? This thing may be focuseable with the elements inspector.

Doing so you could tell me what you see. I'll try to reproduce it.

**Comment by WarpWing** [comment]
Once again, MacOS mystifies me. It fixed it by itself 
![image](https://user-images.githubusercontent.com/28925758/97082083-fd308e80-15d4-11eb-864c-cffe92acf745.png)
Perhaps it was a temporary screen glitch. I'll close this but I'll keep you updated if things go sour. 

Thanks again for your unwavering support!
