### ISSUE TITLE
Exceptions based on window title as well as app name

### ISSUE THREAD

**Issue by d-miketa** [Jean-Tinland/simple-bar#48]
As mentioned in this [Yabai issue](https://github.com/koekeishiya/yabai/issues/74), Microsoft Teams spawns Notification windows with AXWindow/AXStandardWindow subroles so they show up in `simple-bar` processes. It'd be useful to be able to create an exception for windows with the following attributes:
```
{"app":"Microsoft Teams",
"title":"Microsoft Teams Notification"}
```
This way the main Teams window is shown but the extraneous notification windows are hidden from the `spaces` widgets. I've seen Zoom behave in a similar way, so it may be applicable to that case too.

**Comment by Jean-Tinland** [comment]
Hi,

I have implemented a 2nd exclusion field in which you can add all the window titles you want to exclude in the spaces display.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/43068795/97294050-cca75980-184d-11eb-9e60-9337a6909db5.png">

Let me know if this is answering to your problematic.

**Comment by d-miketa** [comment]
Absolutely perfect, thank you! :)
