### ISSUE TITLE
[suggestion] space --label

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#5]
One of the best Übersicht bar, thanks for sharing it 🔥

Would you consider showing the space label if the label is set on a space?

![simple-bar](https://user-images.githubusercontent.com/2527231/92697627-ab1c0c80-f38a-11ea-907c-bbdc936b94a7.png)

**Comment by Jean-Tinland** [comment]
I think it's a great addition. I've made the change!

Thank you for your support!

**Comment by MikoMagni** [comment]
Awesome, thank you

**Comment by Jean-Tinland** [comment]
I forgot to tell you, do not hesitate to ask me to add more apps icons. I just need its name (provided by Yabai) in order to make the link between the app and the icon.

I'll amend the README to let people know they are welcome to ask for more icons by opening issues.

**Comment by MikoMagni** [comment]
Great, good to know.
