### ISSUE TITLE
Conditional Refresh of widgets

### ISSUE THREAD

**Issue by lvadla** [Jean-Tinland/simple-bar#50]
Is there a way to only refresh widgets (utilizing the yabai signals) _if_ Ubersicht is actually running? Whenever I quit Ubersicht, it will immediately restart once yabai emits a signal telling the widgets to refresh

**Comment by lvadla** [comment]
with no luck, I have tried to adjust the .yabairc to this: 
```
# Refresh process widget when current window title changes
yabai -m signal --add event=window_title_changed action="ps cax | grep Übersicht > /dev/null; if [ $? -eq 0 ]; then osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'; fi"

**Comment by JeanTinland** [comment]
Hi!

This could indeed be convenient. I'll look into it this weekend and hopefully quickly find a proper solution.

I'll get back to you here!

**Comment by Jean-Tinland** [comment]
Hi!

This could indeed be convenient. I'll look into it this weekend and hopefully quickly find a proper solution.

I'll get back to you here!

**Comment by lvadla** [comment]
I wrote a little script that might get the job done. Not sure if this is the most elegant solution. Let me know what you think:

```
set appName to "Übersicht"

if application appName is running then
	tell application "Übersicht" to refresh widget id "simple-bar-process-jsx"
end if
```
and then in `.yabairc`:
```
# Refresh process widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript ~/Scripts/refresh-simple-bar-process.scpt"
```

**Comment by Jean-Tinland** [comment]
I've looked into it a bit and it seems that doing simply this:

```sh
# in your .yabairc, replace
yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# by
yabai -m signal --add event=space_changed action="pgrep sicht && osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
```

Is working.

`pgrep sicht` error code prevent widget refreshing.

Let me know if this solves your problem.

**Comment by lvadla** [comment]
working as expected. I have updated my yabai config 👍 cheers
