### ISSUE TITLE
[Question] What is that "stacking"

### ISSUE THREAD

**Issue by christo-ph** [Jean-Tinland/simple-bar#59]
On your web page, I can see in the screenshots, that on the left of your main window is some kind of "app stacking". Is that related to Übersicht or Yabai or Space-Bar?

![image](https://user-images.githubusercontent.com/16965068/100475986-be668a80-30e4-11eb-8387-66d4b0bb7ef5.png)

I would be interested in the workflow in this case.

Bonus Question: Whats that wallpaper =) Is it Star Trek?

**Comment by Jean-Tinland** [comment]
Yabai includes a stacking mode which can be enabled in you yabairc. More information [here](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc).

These icons you see are provided by [Hammerspoon](https://www.hammerspoon.org/) with [Stackline](https://github.com/AdamWagner/stackline) installed.

Not Star Trek, Halo! :) [source here](https://www.deviantart.com/corruptrecluse/art/Halo-316488281)
