### ISSUE TITLE
[question] System Integrity Protection status: unknown (Custom Configuration) 

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#6]
I have SIP partially disabled as per Yabai documentation on MacOS 10.15.6

```
# If you're on macOS 10.14 and above
# (printed warning can be safely ignored)
csrutil enable --without debug --without fs
```

I can create and destroy spaces with skhd however, simple-bar is not displaying the extra options. 

I think it is because csrutil status return

```
System Integrity Protection status: unknown (Custom Configuration) 
````
instead of 

```
System Integrity Protection status: disabled. 
```

And simple-bar is looking for the disabled. 

I will have a better look at it over the weekend but just wanted to ask if there is any reason that you need SIP completely disabled? 

Thanks

**Comment by JeanTinland** [comment]
I could make the opposite test and change:

```javascript
const SIPDisabled = SIP === 'System Integrity Protection status: disabled.'
```

To:
```javascript
const SIPDisabled = SIP !== 'System Integrity Protection status: enabled.'
```

It should work for you but It could break for some other users. 
I think it's doable, tell me what you think.

**Comment by Jean-Tinland** [comment]
I could make the opposite test and change:

```javascript
const SIPDisabled = SIP === 'System Integrity Protection status: disabled.'
```

To:
```javascript
const SIPDisabled = SIP !== 'System Integrity Protection status: enabled.'
```

It should work for you but It could break for some other users. 
I think it's doable, tell me what you think.

**Comment by MikoMagni** [comment]
That worked, thank you!

**Comment by Jean-Tinland** [comment]
I've implemented this modification because it's seems more logical this way: if a user disabled SIP even just a bit then SIP is no longer enabled.

If anyone encounter some problems with this rule I may adjust it or find another way to handle that.

**Comment by DeastinY** [comment]
Just wanted to let you know this has been an issue for me now as well
