### ISSUE TITLE
[Question] Sometimes space-widgets show windows which don't exist

### ISSUE THREAD

**Issue by christo-ph** [Jean-Tinland/simple-bar#61]
Example: Space 4 shows 8 Windows
<img width="547" alt="image" src="https://user-images.githubusercontent.com/16965068/100617530-f22af580-331a-11eb-9b96-8125b1e5fbc0.png">

When I go to space 4, those windows disappear on space 4, appear on space 6:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/16965068/100617632-11298780-331b-11eb-8124-9424106db203.png">

If I click on space 6, those windows appear on space 7:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/16965068/100617749-37e7be00-331b-11eb-9d20-78d8ce5bdd76.png">
(also notice here, that the three windows which really exist in space 6 just appeared correctly)

etc. I've noticed this yet only, if I am making adjustments to my yabai settings and reload everything with `brew service restart yabai` as far as I remember.

Have you seen this? Is that a bug in simple-bar or yabai?

Thanks

**Comment by d-miketa** [comment]
Are you running Microsoft Teams? If so, those are notification-related windows spawned by that application and always kept on a spare (unused) space. It's pretty hacky and could be solved by Teams devs by switching over to the native Mac notifications system, which may or may not happen.

You can exclude them from the spaces display by going to `simple-bar` settings (click on the bar and press `Cmd+,`), navigating to the Spaces tab and setting

`Exclusions by window title name: Microsoft Teams Notification`

**Comment by christo-ph** [comment]
Ah, ok. I use Teams. Slack seems to use the same:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/16965068/100622036-ad09c200-3320-11eb-906a-a49d8d297227.png">

**Comment by Jean-Tinland** [comment]
You'll encounter this issue with Teams, Slack, Skype, the PiP video mode and all apps that are displaying windows on all you screens at once.

The only easy solution is to get for each of these apps the guilty window title name add add it to simple-bar exclusions.

**Comment by christo-ph** [comment]
Thank you @d-miketa & @Jean-Tinland

**Comment by JonathanHuot** [comment]
I guess it will be good to add this into a FAQ/Wiki or similar ?

**Comment by jamieweavis** [comment]
@christo-ph did you figure out the window title name for Slack? 🤔

**Comment by christo-ph** [comment]
@jamieweavis after doing a query with `yabai -m query --windows`

there are several entries with:

```
"title":"Slack | mini panel"
```

so I suppose these should be the ones. Not tried yet.

**Comment by jamieweavis** [comment]
Ah I forgot that you could do that with yabai, yep that works, thanks @christo-ph! ❤️
