### ISSUE TITLE
[Bug] Space labels beginning with numbers

### ISSUE THREAD

**Issue by christo-ph** [Jean-Tinland/simple-bar#62]
Spacelabs beginning with numbers will not be interpreted in the space widget. I tried several forms:

1. "1 Name"
1. "1_Name"
1. "1Name"

The space will be shown as the space number, no name at all.

Having a number on pos >1 is working properly.

**Comment by Jean-Tinland** [comment]
I think this is related to yabai not allowing label names starting with a number:
![image](https://user-images.githubusercontent.com/43068795/100624661-fc9dbd00-3323-11eb-88b6-aa70e1ebe470.png)
