### ISSUE TITLE
[Error] Spaces and process erroring out

### ISSUE THREAD

**Issue by milse113** [Jean-Tinland/simple-bar#66]
simple-bar-spaces.jsx and simple-bar-process.jsx both throwing "Something went wrong..."; Console spamming 500 errors

MacOS Catalina 10.15.5 with Yabai; Not exactly sure what I should provide, feel free to ask anything you need

**Comment by milse113** [comment]
I did some debugging, made a fix; Had to do with with where I put my dotfiles

**Comment by codemangle101** [comment]
Same error is happening when the default MacOS shell isn't bash. If you are on something like zsh then please check the option in uberschit preferences "Load bash env".

**Comment by Jean-Tinland** [comment]
The default shell used by simple-bar bar is "sh". You can change it in simple-bar settings.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/43068795/101241189-56bbcb00-36f4-11eb-88d8-7eb5ca0b7f24.png">

Let me know if that helps you.

**Comment by codemangle101** [comment]
It's working fine with sh in settings without changing preference in uberschit. Not sure why it behaved like that before.

**Comment by Jean-Tinland** [comment]
Okay, feel free to re open this issue if necessary!
