### ISSUE TITLE
Very high CPU usage.

### ISSUE THREAD

**Issue by codemangle101** [Jean-Tinland/simple-bar#67]
This line is causing too much CPU usage on default installation.
https://github.com/Jean-Tinland/simple-bar/blob/b1b48e6832cd018576d44530639564c431584c36/lib/utils.js#L145

**Comment by MikoMagni** [comment]
`simple-bar-spaces-2-jsx` is no longer used since this PR https://github.com/Jean-Tinland/simple-bar/pull/54
You should be able to remove that line without causing any issues.

**Comment by Jean-Tinland** [comment]
Indeed, I juste removed this line. It was an oversight. Thanks for the catch @codemangle101 & @MikoMagni. :)
