### ISSUE TITLE
So this bar is absolutely stunning. Would you consider designing something similar for polybar on arch based machines? 

### ISSUE THREAD

**Issue by Eoin-McMahon** [Jean-Tinland/simple-bar#7]

**Comment by Jean-Tinland** [comment]
Hi,
Unfortunately I've never worked with polybar and never developed any thing in a Linux environment.
You could probably ask someone who has worked on a polybar config showing this project as an example.

**Comment by Jean-Tinland** [comment]
Hi again @Eoin-McMahon 
I just saw on Unixporn subreddit a post which may provide you what you needed: [this post](https://www.reddit.com/r/unixporn/comments/j4he3v/bspwm_blossom/).

You can check the comments for polybar config and ask OP for more information.
