### ISSUE TITLE
Remove/toggle process name

### ISSUE THREAD

**Issue by darrikonn** [Jean-Tinland/simple-bar#71]
I'd like to remove the process name which is rendered in the middle (but need the component for Settings).

Is it possible to toggle this on/off?

Quite disturbing navigating in the shell and seeing this flashing due to a re-render when a directory is switched.

(The Process component)

**Comment by Jean-Tinland** [comment]
Done, you can toggle this part of the bar in the settings module ("Widgets" tab).

**Comment by darrikonn** [comment]
Awesome, thanks!
