### ISSUE TITLE
Feature request: Show current keyboard input source

### ISSUE THREAD

**Issue by darrikonn** [Jean-Tinland/simple-bar#72]
Would be nice to add a widget for the current input source, and re-render from a yabai signal

**Comment by Jean-Tinland** [comment]
I don't think a yabai signal for current input source switch exists: see [supported signals list](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#673-event).

However I can add an optional widget which would display the current layout name. This widget would be refreshed every 10 seconds, same as all data widgets.

**Comment by darrikonn** [comment]
Sounds good.

**Comment by Jean-Tinland** [comment]
Done, you can activate this new widget in the "Widgets" tab in settings (`cmd + ,` after clicking in the middle of the bar).

Let me know if you encounter any problem, I don't know for sure if the command retrieving the keyboard information is working for everyone.

**Comment by darrikonn** [comment]
Works like a charm :)!
Thanks!
