### ISSUE TITLE
Is there a way to add left and right padding to the bar?

### ISSUE THREAD

**Issue by tbsmn** [Jean-Tinland/simple-bar#74]
Hi I like this bar very much. Nice work!

I was wondering if there is a way to add a padding to the left and right side. So when using with yabai and padding it can be aligned.

**Comment by Jean-Tinland** [comment]
Hi, thank you!

There is indeed a way to make any change you wan't. I added a file in which you can add custom styles (in CSS) : `lib/styles/CustomStyles.js` but first you'll need to check the "Floating bar" option in settings.

For example, if you want to add a padding of 25px on left & right, I suggest you add these styles below:

```javascript
const CustomStyles = /* css */ `
.simple-bar {
  top: 10px;
}
.simple-bar--spaces {
  left: 25px;
}
.simple-bar--process {
  left: 25px;
  width: calc(100% - 50px);
  border-radius: 3px;
}
.simple-bar--data {
  right: 25px;
}
`

export default CustomStyles
```

You can simply copy/paste that and replace everything that is already in this `CustomStyles.js` file.

Procceding trought these 2 steps you should obtain something like that:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/43068795/102626940-c778d380-4147-11eb-8134-7ac5fd25f457.png">

**Comment by tbsmn** [comment]
Thank you for that fast response!
Works perfekt!

**Comment by bbamnesia** [comment]
Hi,

 I want to increase the padding from the top, but I dont see the CustomStyles file youre talking about.

**Comment by Jean-Tinland** [comment]
Hi, custom styles are now managed directly in the bar settings ("Custom styles" tab). :)

**Comment by bbamnesia** [comment]
> Hi, custom styles are now managed directly in the bar settings ("Custom styles" tab). :)

Thanks, I inputted the following into the Custom Styles tab:

.simple-bar {
  top: 8px;
}
.simple-bar--spaces {
  left: 100px;
}
.simple-bar--process {
  left: 25px;
  width: calc(100% - 50px);
  border-radius: 3px;
}
.simple-bar--data {
  right: 100px;
}

and only the top padding seems to works, no matter what i put for the left and right data, it does not seem to work. I am using floating bar if that makes a difference.
