### ISSUE TITLE
[Error] Invalid hook call

### ISSUE THREAD

**Issue by JolyCoder** [Jean-Tinland/simple-bar#77]
What it is?
![image](https://user-images.githubusercontent.com/17800971/102622963-d2853100-4152-11eb-9cc6-fc5c0b047aa3.png)
macOS Catalina 10.15.6

**Comment by Jean-Tinland** [comment]
Are you sure your Übersicht is up to date? It looks like it's using the wrong React version.

**Comment by Jean-Tinland** [comment]
I'm closing this for now, feel free to open it again if you are still stuck with this problem. :)
