### ISSUE TITLE
feature request: add "highlight" color for current space on inactive display

### ISSUE THREAD

**Issue by hpl002** [Jean-Tinland/simple-bar#79]
The title is poor, but i struggle to explain this simply so i provide some images instead.

I am often running into issues where i am moving a window from one display to the next and then end up sending the window to the incorrect space because there is no indication of what space is currently being shown on the inactive display. 

## Story
I have the following windows and spaces on **Display 1**. 
<img width="299" alt="Screenshot 2020-12-24 at 12 39 54" src="https://user-images.githubusercontent.com/25330262/103086738-a0a61b80-45e5-11eb-9bde-43a21762ca7a.png">

Here we can clearly see that space 1 has two apps (vscode and spotify), the others are full screen. I now want to move vscode to one of my other displays, say **Display 2** 

**Display 2** has these spaces:
![Screenshot 2020-12-24 at 12 44 13](https://user-images.githubusercontent.com/25330262/103086776-be738080-45e5-11eb-8473-f4d8425572fe.png)

At a glance i can see that Display 2 is not displaying full screen so the only options are space 5 or 7. This is the point where i have to either make the target display active so that the i know the index of the active space on that display, or simply make an educated guess. Most of the time i end up missing..

**Would it be possible to add a secondary color that would indicate what the current _active_ space is on every _inactive_ display?**

**Comment by hpl002** [comment]
I can of course take a stab at a PR if this is something that anyone besides me would find useful and if it isn't already configurable.

**Comment by Jean-Tinland** [comment]
Hi, I see exactly what your problem is, thank you for the explanation. 

I'll look into it and I'll see if I can find a nice answer to this.

I'll keep you updated here :)

**Comment by Jean-Tinland** [comment]
I added an indicator on the visible space for the inactive/not currently focused display. Let me know if this is OK.

**Comment by hpl002** [comment]
**Perfect!**

Thanks for getting around to this so quickly! 

Keep up the good work 👌👌
