### ISSUE TITLE
simple-bar not recognized by yabai

### ISSUE THREAD

**Issue by SinistreCyborg** [Jean-Tinland/simple-bar#80]
For some reason, yabai doesn't recognize the presence of simple-bar at the top and puts windows on top of the bar itself. How can I fix that? Here are my [dotfiles](https://github.com/SinistreCyborg/dots).
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/53885408/103111024-6143f300-4616-11eb-98bf-8b21e9b0f302.png">

**Comment by Jean-Tinland** [comment]
Hi!

You simply need to add this line in your `.yabairc`:

```sh
yabai -m config external_bar                 all:28:0
```

Where 28 is the top padding & 0 the bottom one.
28 is the default height of simple-bar, you may need to adjust it to match your setup.

My yabai layout config looks like that:

```sh
yabai -m config layout                       stack # bsp
yabai -m config top_padding                  25
yabai -m config bottom_padding               25
yabai -m config left_padding                 25
yabai -m config right_padding                25
yabai -m config window_gap                   20
yabai -m config external_bar                 all:28:0
```

Let me know if this solves your problem.

Merry Christmas :)

**Comment by SinistreCyborg** [comment]
That seems to work. Thanks, and merry christmas to you too!
