### ISSUE TITLE
Can't create workspaces despite SIP being disabled.

### ISSUE THREAD

**Issue by Obl1que** [Jean-Tinland/simple-bar#82]
I have SIP disabled on my macbook, yet when I try to create new workspaces with simple-bar, it plays the animation etc., but nothing else happens. When i run csrutil status, I get
"System Integrity Protection status: disabled." I am on MacOS Big Sur, and all the other widgets etc. work fine.

**Comment by Tchoupinax** [comment]
Hello,

I am in a similar state. My SPI is disabled, the animation is done when clicking on the button but nothing happens.

```
あ→ csrutil status
System Integrity Protection status: disabled.
```

I'm on MacOS Big Sur 11.0.1

**Comment by Tchoupinax** [comment]
@Obl1que I found the solution.

It appears you should reload the scripting-addition with `sudo yabai --load-sa`. When I tried to manually create a space I met the following error : 

```
あ→ yabai -m space --create
cannot create space due to an error with the scripting-addition.
```

I met this error earlier in the day and I reload the configuration. It was working. I'm afraid that the restart resets the scripting-addition for Yabai... but anyway if there is an issue it is a Yabai's issue.

Once Yabai correctly installed, the bar works well !

**Comment by Jean-Tinland** [comment]
Hi, thank you for your researches, there has indeed been some changes in the Yabai installation process since Big Sur arrived.

I'll put a reminder in my readme file providing this link.

**Comment by Obl1que** [comment]
Thanks, works great now!

**Comment by Obl1que** [comment]
Works great now! Thanks!

**Comment by kirkegaard** [comment]
This seems to be back in 11.2. I dont think its a script issue, more like a yabai vs big sur issue :)
Ive added a comment on it here https://github.com/koekeishiya/yabai/issues/763#issuecomment-767904774

Have anyone else had this problem?

**Comment by yanzhang0219** [comment]
To adapt to the new macOS version, I think a new payload code should be used. Just stay tuned and the author will make it as soon as its official version is released.
