### ISSUE TITLE
simple-bar-data.jsx crashes when spotify goes into idle state

### ISSUE THREAD

**Issue by lvadla** [Jean-Tinland/simple-bar#85]
`simple-bar-data.jsx: Something went wrong...` when my Spotify session finishes (the queue is empty and "autoplay similar music when finished" is disabled).

I tried to add a console log stmt to `data.jsx` like you mentioned in a previous issue but it came back undefined.

Here is the Spotify idle state I am referring to:

![Screen Shot 2021-01-06 at 6 27 49 PM](https://user-images.githubusercontent.com/25832339/103800605-e4b90780-504c-11eb-9cf9-d59e7af3d89e.png)

**Comment by Jean-Tinland** [comment]
Hi, there indeed as been some problem with the Spotify widget in idle state. Thank you for the detail, I'll reproduce exactly this an will try to fix the problem as soon as possible.

I'll keep you updated here.

**Comment by Jean-Tinland** [comment]
I'm stuck on this for now as I can't find a way to enter this idle state. Each time my queue finally get empty, Spotify add the first song I originally added to my queue and stays on it without launching it.

I'll keep you posted about that.

**Comment by lvadla** [comment]
Hi @Jean-Tinland, perhaps you could try playing a single podcast episode with "Repeat" turned off?

**Comment by Jean-Tinland** [comment]
I tried exactly that whithout success, I'll keep watching closely my logs while listening to Spotify hoping to reproduce your issue.

I was also wondering if you were using the latest version of the Spotify desktop app?

**Comment by Jean-Tinland** [comment]
I just added a potential fix in which I added a "stopped" state to the Spotify widget.

As I can't test it let me know if this is better.

**Comment by shepherdjerred** [comment]
I'll pull your changes and see if it happens again.

**Comment by lvadla** [comment]
This seems to fix the issue I was seeing 😄

**Comment by Jean-Tinland** [comment]
That's good news! I'll close this, feel free to open it again or create a new issue if you encounter any problem.
