### ISSUE TITLE
Workspace indicator doesn't change. 

### ISSUE THREAD

**Issue by notaduck** [Jean-Tinland/simple-bar#86]
I recently installed the lates version of yabai through brew, then Ubersict and simple-bar, and so far it looks impressing. However the indicator is stuck at workspace/desktop 1.

**Comment by Jean-Tinland** [comment]
Hi, thank you for using simple-bar and for the compliment!

It looks like you haven't added the signals in you .yabairc file. Check [this part of the readme](https://github.com/Jean-Tinland/simple-bar#refresh-bar-on-app-or-workspace-change) and let me know if this solves the issue.

**Comment by notaduck** [comment]
I totally missed that!
