### ISSUE TITLE
Overlappings occur with multiple screen.

### ISSUE THREAD

**Issue by ro-n** [Jean-Tinland/simple-bar#87]
With multiple monitors, simple-bar works on numbering the workspaces (desktops), but overlaps with others' tabs.

First screen:

![image](https://user-images.githubusercontent.com/66688118/104089540-e97af700-52aa-11eb-9d9c-60d32bc5fd5b.png)

Second screen:

![image](https://user-images.githubusercontent.com/66688118/104089553-fb5c9a00-52aa-11eb-9df0-049361d672d2.png)

**Comment by Jean-Tinland** [comment]
Can you show me you widget list? It looks like thu `simple-bar-spaces` widget is running twice.

Your widget list should look like that:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/43068795/104135220-0b4daa00-538f-11eb-8228-ff07fcb55a49.png">

**Comment by ro-n** [comment]
Indeed, 
![image](https://user-images.githubusercontent.com/66688118/104270536-b7001280-54d3-11eb-9ef2-47f2f9c33fc5.png).

Thanks, solved by setting `Show on selected screens` correspond to each screen (display monitor).

**Comment by Jean-Tinland** [comment]
It looks like you are using an old version of simple-bar. If you pull the latest commits you'll have only one "spaces" widget which will handle **n** monitors by itself.
