### ISSUE TITLE
Make network device configurable

### ISSUE THREAD

**Issue by shepherdjerred** [Jean-Tinland/simple-bar#88]
My Mac Mini has both WiFi and ethernet. This caused simple-bar to not work properly until I edited the source so that it queried en1 instead of en0 (See [this patch](https://github.com/shepherdjerred/simple-bar/commit/c07bbc8c12f96f23725c1dbe67a8fb431a70d713)).

Can the network device either be made configurable or auto-detected somehow?

**Comment by Jean-Tinland** [comment]
The displayed network is indeed hardcoded, I'm planning to introduce at least a field in simple-bar settings letting the user override the default network source. Maybe I'll find a clean solution for setting it automatically!

**Comment by Jean-Tinland** [comment]
Hi, I couldn't achieve automatic network device detection (for now) so I added like you suggested a setting which allow the user to manually set the right network source for simple-bar to show.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/43068795/104460642-a40e4080-55ae-11eb-8ca6-c51a3b8a88b5.png">

Let me know if it suits you :)

**Comment by shepherdjerred** [comment]
This is perfect!!! Thank you.
