### ISSUE TITLE
Patreon/GitHub sponsor

### ISSUE THREAD

**Issue by shepherdjerred** [Jean-Tinland/simple-bar#89]
Do you have a site where you accept recurring donations? I use this software and would love to contribute a small amount monthly to thank you for your work on it.

**Comment by Jean-Tinland** [comment]
Thank you very much for your support, I must admit that I hadn't anticipated this, you are the first to ask me! If I have more messages like yours in the future It might be an option but for now I haven't got anything set up.

I'll keep you posted, thanks again I really appreciate it.

**Comment by Jean-Tinland** [comment]
I finally made the procedure in order to enable _Github Sponsors_ on my account. This is obviously a "bonus" thing and with or without it I'll continue to maintain this project as long as I can. 

Anyway, every compliments mean already a lot to me.
