### ISSUE TITLE
Add simple Weather to Bar

### ISSUE THREAD

**Issue by flewid** [Jean-Tinland/simple-bar#90]
It would be nice to have simple weather on the statusbar, like ayu-nibar does it 

https://github.com/ryanyz10/ayu-nibar

**Comment by Jean-Tinland** [comment]
That's a great suggestion, I can give it a try!

**Comment by Jean-Tinland** [comment]
If you pull the latest commit you'll find a Weather widget. You can activate it in settings. 

Let me know if you encounter any problem.

**Comment by flewid** [comment]
hey cool! so mine shows <cloud> , -2C 

how do i set my location?

**Comment by Jean-Tinland** [comment]
You need to allow Übersicht access to your location. A popup should have opened when you activated the weather widget. You can manually enable it in macos settings.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/43068795/104822937-8c50e980-5846-11eb-84f3-23b340c0712d.png">


I'll add a field in settings letting the user manually set a location. If nothing is set in this field, simple-bar will use the user geolocation.

**Comment by Jean-Tinland** [comment]
There is an issue which prevent the widget from working, I'm fixing it right now.

**Comment by Jean-Tinland** [comment]
Everything should be settled now, let me know if this is better.

**Comment by flewid** [comment]
Cool, works now thank you. I did not receive the popup initially, however it was there in settings. It seems that when I have 'colors' checked off it's still colored though, with a 'rainbow' ish background. Here's a screen 

https://www.dropbox.com/s/yifr5jy04sg2lc7/Screen%20Shot%202021-01-16%20at%205.44.42%20PM.png?dl=0

**Comment by Jean-Tinland** [comment]
There is indeed a special background during sunset & sunrise. I'll disable it in "no color" mode.

**Comment by flewid** [comment]
Thank you!

**Comment by MikoMagni** [comment]
@Jean-Tinland very nice addition! Would it be possible to add a toggle to only show the temperature without the location name to keep Simple Bar smaller?  

<img width="162" alt="Screen Shot 2021-01-18 at 10 28 13 am" src="https://user-images.githubusercontent.com/2527231/104859863-059c2980-5978-11eb-9724-2b929fce96ef.png">

**Comment by flewid** [comment]
I like @MikoMagni 's Idea as well. 

Plus it's kind of weird, but it's been dark now for 2 hours, and it's still showing me the sun icon?

![g7mKT7LQ](https://user-images.githubusercontent.com/959439/104859948-b8c43e80-58f6-11eb-9664-de5473e1bbe0.png)

**Comment by Jean-Tinland** [comment]
Thank you for your suggestions.
I fixed some issues & added some options in settings for this weather widget:

1. No mode gradient background in "no color" mode (dark & light theme).
2. Hide/show location (checkbox in settings).
3. Clear sky at night now result in a Moon icon instead of a Sunny one.

**Comment by MikoMagni** [comment]
Thank you @Jean-Tinland

**Comment by flewid** [comment]
Great thanks, looks good.

**Comment by Jean-Tinland** [comment]
As it seems stable enough, I'll close this for now, feel free to re open it or create a new issue if necessary. Thank you for your help!

**Comment by flewid** [comment]
Thank you. I also noticed one more thing - I'm using the PyWal version for coloring (works great), however, now the gradient during sunrise/sunset is back (however, it's matching the PyWal colors now). Is it possible to have a checkbox to turn that feature off?

**Comment by Jean-Tinland** [comment]
Done :)

**Comment by flewid** [comment]
Cool thank you!
