### ISSUE TITLE
Spotify from Spotifyd/Spotify-Tui

### ISSUE THREAD

**Issue by flewid** [Jean-Tinland/simple-bar#92]
Sorry for so many tickets! 

I have been using spotify-tui lately, but it doesn't show current track in simple-bar like using the regular spotify client does, any possibility to get that integrated?

**Comment by Jean-Tinland** [comment]
No problem, I'm glad to add new features & improve this little project in any way I can. 

I'll look into this, stay tuned. :)

**Comment by Jean-Tinland** [comment]
It may be harder than expected since I can make spotifyd & spotify-tui work together for now. I'll keep you posted!

**Comment by flewid** [comment]
okay no problem nor rush, they are kind of a pain to get working - i had to install both from source, not from the brew packages on my mac then it all magically started working

**Comment by AlexMeuer** [comment]
We can get the current track and artist from `spt` but I haven't found a way to get the playing status. `spotifyd` allows you to provide a script to run whenever there's an event (e.g. load, play, pause, volumeset, ...) but I haven't found a non-hacky way to integrate that with `get_data.sh`.

     SPOTIFYD_TRACK_NAME=$(spt playback -f '%t')
     SPOTIFYD_ARTIST_NAME=$(spt playback -f '%a')

If `spt` has been paused for a while, then `spt playback` completes with an error code, but it's not a reliable way to know if it's paused or not.

**Comment by flewid** [comment]
ahh okay, not a huge deal :) 
thanks for checking

**Comment by Jean-Tinland** [comment]
As I can't explore this further, I'm closing this for now. 

If anyone else finds a solution, then feel free to open it again or open a new issue. :)
