### ISSUE TITLE
cmd + f in browser breaks simple-bar-process.jsx

### ISSUE THREAD

**Issue by yorhodes** [Jean-Tinland/simple-bar#93]
```SyntaxError: JSON Parse error: Unterminated string```

**Comment by Jean-Tinland** [comment]
Indeed, I'll look into it, thanks!

**Comment by Jean-Tinland** [comment]
This should be resolved now.

**Comment by yorhodes** [comment]
Can confirm.

Closed in 2b4dc694dea152abd308b80168850780ddd41079.
