### ISSUE TITLE
Support for Viscosity

### ISSUE THREAD

**Issue by d-miketa** [Jean-Tinland/simple-bar#96]
I wrote a small widget to connect to and disconnect from a VPN using Viscosity. Would there be any interest in submitting it upstream?

**Comment by Jean-Tinland** [comment]
Sure! You can submit a pull request and I'll merge it as an optional widget disabled by default.

**Comment by d-miketa** [comment]
Done, but it's my first one (yay) – let me know if it's too messy etc.

**Comment by Jean-Tinland** [comment]
Merged in master. :)
