### ISSUE TITLE
Simple-Bar Refresh / Workspace Issues

### ISSUE THREAD

**Issue by zacharyFerretti** [Jean-Tinland/simple-bar#99]
Hi! Sorry if this is the wrong place to post it but not sure where else it would belong. 

I've installed `Yabai`, `Übersicht`, and lastly `simple-bar` this morning on my Macbook (15" Running macOS Big Sur 11.0.1). 

Unfortunately I've noticed that the workspace functionality isn't seeming to work consistently and I'm not sure if this is a problem on my end or if there is something I had installed incorrectly. 

My understanding of the workspace functionality is that it's supposed to represent the different `Virtual Desktops` that you can create on a Mac, and this functionality is one of the main factors that attracted my to `simple-bar`! 

However I'm having problems with the workspace and titlebar functionality not actually working. The behaviors I've seen that stray from what is displayed [here]( https://www.reddit.com/r/unixporn/comments/kzx1qj/yabaimacos_highly_customizable_status_bar_with/) are:

1. Workspaces can't actually be created or deleted (I've confirmed `csrutil status` returns disabled since I know you mention SIP needs to be disabled for that functionality). 
2. Workspaces do not automatically update with what applications are open in them, for example I would open `iterm` and it does not actually add the `iterm` icon in the open workspace.
3. Lastly unfortunately the titlebar does not actually represent what window is currently open. 

I think this is a problem with how `Übersicht` is handling refreshing, because if I manually change the `simple-bar` menu color or theme then it does refresh (albeit it takes around ten seconds for the theme to change). 

Is there anything that you can think of that I should be doing which I'm not? 

I've read through the docs for both `Yabai` and `Übersicht` and I'm fairly certain I've configured them both properly for what I'm trying to do with them so I'm not sure what else I should do. I would be happy to provide any further data I could to help figure out what's going wrong. Thanks again, it's an awesome piece of software just wanna get it working!

**Comment by Jean-Tinland** [comment]
Hi thanks for the compliments! Are you sure you added  all the signals necessary for making simple-bar responsive to workspaces changes?
See [this readme](https://github.com/Jean-Tinland/simple-bar#refresh-bar-on-app-or-workspace-change) section.

Let me know if this helps you!

**Comment by zacharyFerretti** [comment]
Hi Jean, thanks for that link I added those sections and that's fixed _almost_ all the issues! The reason I hadn't installed it originally was because I had been following the installation instructions listed on the [simple-bar site](https://www.simple-bar.com/en/). 

Now the Titlebar updates as I change apps which it wasn't doing before, awesome. 

The icons in the different workspaces update depending on when apps are opened, and if I switch workspaces it properly highlights which space I am in. 

However I'm _still_ unable to create or delete workspaces with the different places icons at the top of the status bar on the left. It's strange because earlier today I was able to create workspaces before that ability stopped working. `csrutil status` is still telling me SIP is disabled. 

If you aren't sure what I could be missing it's okay if I can't create / switch workspaces with what's at the top. If that's the case would re-enablling SIP impact the titlebar / app icons and workspace highlighting?

Or is SIP only necessary for creating, deleting, and moving between workspaces?

**Comment by Jean-Tinland** [comment]
Oh, indeed, I need to update the website about that part, thanks for the catch!

In order to create/delete workspaces, `simple-bar` is using `yabai` commands. You can try to run theses commands directly in your terminal and look a the output.

For example, try:
```sh
yabai -m space --create
```

If this command isn't working, you can check if you correctly installed `yabai`, there are some tricky stuff to think about when installing it. See [this](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup) for activating the scripting addition.

**Comment by Jean-Tinland** [comment]
I'm closing this for now, feel free to re open it if necessary. :)
